LID_1active=1个激活
LID_1channelactive=1个激活频道
LID_1channelpassive=1个被动频道
LID_1passive=1个被动
LID_ability=能力
LID_about=关于
LID_accept=接受
LID_accepthit=接受悬赏
LID_access=权限
LID_account=账户
LID_active=激活
LID_add=添加
LID_added=已添加
LID_addentry=添加条目
LID_admin=管理员
LID_administrator=管理员
LID_adminmode=管理员模式
LID_adminnotification=管理员通知
LID_adminonly=仅限管理员
LID_advanced=高级
LID_advert=注意
LID_afk=离开
LID_agility=敏捷
LID_all=全部
LID_allbuildingsunlocked=所有建筑已解锁
LID_ammo=弹药
LID_ammunation=军火商
LID_angle=角度
LID_antipropkill=反道具杀
LID_appearance=外貌
LID_areyousure=你确定吗？
LID_armor=护甲值
LID_arms=手臂
LID_arrest=逮捕
LID_arrests=逮捕记录
LID_arreststick=逮捕棒
LID_attribute=属性
LID_attributes=属性
LID_automaticmapchangeinx=X后自动切换地图
LID_autopickup=自动拾取
LID_back=退回
LID_background=背景
LID_backpack=背包
LID_bag=包
LID_ban=封禁
LID_bandage=绷带
LID_bandages=绷带
LID_bandaging=正在包扎
LID_batteringram=攻城锤
LID_becomerole=成为角色
LID_birthday=生日
LID_blind=致盲
LID_blinded=已致盲
LID_bodyheight=身高
LID_border=边框
LID_bring=召唤
LID_building=建筑
LID_buildings=建筑
LID_buy=购买
LID_buymenu=购买菜单
LID_canbeowned=可被拥有
LID_cancel=取消
LID_cannotbedropped=%ITEM% 无法被丢弃
LID_card=卡片
LID_categories=类别
LID_category=类别
LID_cell=牢房
LID_change=更换
LID_changecharacter=更换角色
LID_changed=更换
LID_changefaction=更换阵营
LID_changelog=更改日志
LID_charactermenu=角色菜单
LID_characterselection=选择角色
LID_characterssettings=角色设置
LID_chat=聊天
LID_chest=胸
LID_client=客户端
LID_clients=客户端
LID_cloak=隐身
LID_cloaked=已隐身
LID_clock=时钟
LID_close=关闭
LID_collection=收藏
LID_color=颜色
LID_colors=颜色
LID_comlink=通讯链接
LID_command=指令
LID_commands=指令
LID_community=社区
LID_compass=指南针
LID_confirm=确认
LID_connect=连接
LID_connected=连接
LID_connecting=连接中
LID_connection=连接
LID_connections=连接
LID_contact=联系方式
LID_contries=国家
LID_cooldown=冷却时间
LID_cooler=散热器
LID_coowner=共同所有者
LID_coowners=共同所有者
LID_copyrpname=复制RP名称
LID_copysteamid=复制SteamID
LID_copysteamid64=复制SteamID64
LID_copysteamname=复制Steam名称
LID_country=国家
LID_coverears=捂耳朵
LID_cpu=CPU
LID_create=创建
LID_createcharacter=创建角色
LID_createhit=创建悬赏
LID_crossarms=交叉手臂
LID_crossarmsbehind=交叉手臂(背后)
LID_cuffed=已被铐住
LID_currentuptime=当前运行时间
LID_currentversion=当前版本
LID_custom=自定义
LID_customize=自定义
LID_damage=伤害
LID_damaged=伤害
LID_dark=深色
LID_dashboard=仪表盘
LID_database=数据库
LID_day=天
LID_days=天
LID_dead=死亡
LID_dealer=经销商
LID_dealers=经销商
LID_death=死亡数
LID_deaths=死亡数
LID_deathscreen=死亡界面
LID_decline=拒绝
LID_decreaseviewingheight=降低观察高度
LID_default=默认
LID_defaults=默认设置
LID_delete=删除
LID_deleteentry=删除条目
LID_description=描述
LID_developer=开发者
LID_disable=禁用
LID_disabled=禁用
LID_disconnect=断开连接
LID_disconnected=断开连接
LID_disconnecting=断开连接中
LID_displayname=显示名称
LID_distance=距离
LID_dnd=请勿打扰
LID_done=完成
LID_door=门
LID_doors=门
LID_downloadlatestversion=下载最新版本
LID_drag=拖拽
LID_drink=饮料
LID_drinking=饮水中
LID_drop=丢下
LID_dropitem=丢下物品
LID_dropweapon=丢下武器
LID_east=东
LID_east_short=东
LID_eating=进食中
LID_edit=编辑
LID_emote=表情
LID_emoteagree=同意
LID_emotebecon=召唤手势
LID_emotebow=鞠躬
LID_emotecheer=欢呼
LID_emotedancenormal=普通舞蹈
LID_emotedancerobot=机器人舞蹈
LID_emotedancesexy=性感舞蹈
LID_emotedisagree=不同意
LID_emoteforward=前进
LID_emotegroup=集合
LID_emotehalt=停止
LID_emoteimitiationzombie=模仿僵尸
LID_emotelaugh=大笑
LID_emotepers=惊吓
LID_emotes=表情
LID_emotesalute=敬礼
LID_emotewave=挥手
LID_emotion=表情
LID_empty=空
LID_enable=启用
LID_enabled=启用
LID_energy=能量
LID_entered=已输入
LID_enterworld=进入世界
LID_enteryourfirstname=输入你的名字
LID_enteryoursurname=输入你的姓氏
LID_entities=实体
LID_entity=实体
LID_entspawner=实体生成器
LID_environment=环境
LID_equip=装备
LID_equipment=设备
LID_event=活动
LID_exit=退出
LID_export=导出
LID_extinguish=熄灭
LID_facepalm=捂脸
LID_faction=阵营
LID_factions=阵营
LID_factor=系数
LID_feedback=反馈
LID_food=食物
LID_force=强制
LID_forcesetkeybinds=强制设置按键绑定
LID_fpp=第一人称
LID_fppr=真实第一人称
LID_fps=帧数
LID_frag=击杀数
LID_frags=击杀数
LID_freeze=冻结
LID_from=从
LID_frozen=已冻结
LID_fuel=燃料
LID_fuelup=加油
LID_full=已满
LID_gadget=装备
LID_gadgets=装备
LID_gadgetslot=装备槽
LID_gadgetslots=装备槽
LID_gamemodedeveloper=游戏模式开发者
LID_gamemodetranslator=游戏模式翻译者
LID_gap=间距
LID_gather=采集
LID_gender=性别
LID_genderfemale=女性
LID_gendermale=男性
LID_genderother=其他性别
LID_general=一般
LID_getlivesupport=在线帮助
LID_getrole=获得角色
LID_githubversion=Github版本
LID_give=给予
LID_givefeedback=反馈错误
LID_globalchat=全局
LID_god=无敌模式
LID_group=分组
LID_grouplogo=群组标志
LID_groupmenu=群组菜单
LID_groups=分组
LID_handcuffed=手铐
LID_handcuffs=手铐
LID_hasbeendropped=%ITEM% 已被丢弃
LID_hasfinishedloading=%NAME% 已完成加载
LID_head=头
LID_header=标题
LID_health=生命值
LID_hearq=能听到吗？
LID_height=高度
LID_help=帮助
LID_helpmenu=帮助菜单
LID_hide=隐藏
LID_hided=隐藏
LID_hip=臀部
LID_holdtozoominview=按住放大视图
LID_holdtozoomoutview=按住缩小视图
LID_hololink=全息链接
LID_hostname=主机地址
LID_hour=小时
LID_hours=小时
LID_hover=悬停
LID_hovered=已悬停
LID_hoverover=悬停于
LID_hud=HUD
LID_hungry=饥饿
LID_hygiene=卫生
LID_iamstuck=我卡住了
LID_icon=图标
LID_icons=图标
LID_id=ID
LID_idcard=身份证
LID_idcardid=身份证ID
LID_identifier=标识符
LID_identifycard=身份识别卡
LID_identitycard=身份证
LID_idstructure=ID结构
LID_ignite=点燃
LID_import=导入
LID_in_use=使用
LID_increaseviewingheight=提高观察高度
LID_info=信息
LID_information=信息
LID_intellect=智力
LID_inventory=库存
LID_invitation=邀请
LID_invitetofaction=邀请加入阵营
LID_invitetogroup=邀请加入群组
LID_ip=ip地址
LID_iscp=是民防人员
LID_isloading=正在加载
LID_ismayor=是市长
LID_ismedic=是医疗人员
LID_it=它
LID_item=物品
LID_items=物品
LID_jail=监狱
LID_join=加入
LID_key=钥匙
LID_keybindsmenu=按键绑定菜单
LID_keyinsert=Insert键
LID_keynumpad=数字键盘
LID_keypage=Page键
LID_keys=钥匙
LID_kick=踢出
LID_kill=击杀
LID_kills=击杀数
LID_kneeling=跪下
LID_language=语言
LID_languages=语言
LID_law=法律
LID_laws=法律
LID_lawsymbol=法律符号
LID_leave=离开
LID_legs=腿部
LID_length=长度
LID_level=等级
LID_levelsystem=等级系统
LID_levelup=升级
LID_levelx=等级 %LEVEL%
LID_license=执照
LID_licenses=执照
LID_light=浅色
LID_loaded=已加载
LID_loading=加载中
LID_loadingdata=正在加载数据
LID_loadingdesign=正在加载设计
LID_localchat=本地
LID_lock=上锁
LID_lockdown=封锁
LID_lockdowntext=封锁文本
LID_locked=上锁
LID_lockeddoor=门已上锁
LID_lockedvehicle=车辆已上锁
LID_locking=上锁中
LID_lockpick=撬锁工具
LID_lockpicking=正在撬锁
LID_logo=标志
LID_logout=登出
LID_logouttime=登出时间
LID_logs_settings=日志(设置)
LID_looc=当前的性格
LID_lostconnection=连接丢失
LID_macromenu=宏菜单
LID_mana=法力
LID_manually=手动
LID_map=地图
LID_maps=地图
LID_max=最大
LID_maxactive=最大激活数
LID_maximumlevel=最高等级
LID_maximumsize=最大尺寸
LID_maxpassive=最大被动数
LID_me=我
LID_member=成员
LID_members=成员
LID_menu=菜单
LID_menus=菜单
LID_middlefinger=竖中指
LID_min=最小
LID_minimap=小地图
LID_minimumlevel=最低等级
LID_minimumsize=最小尺寸
LID_minute=分钟
LID_minutes=分钟
LID_mode=模式
LID_model=模型
LID_models=模型
LID_money=金钱
LID_money_printer=印钞机
LID_month=月
LID_months=月
LID_moreinformation=更多信息
LID_motd=每日消息
LID_multiplier=乘数
LID_mutevoice=静音语音
LID_name=名字
LID_namechangeable=名称可更改
LID_nameistolong=名字太长
LID_nameistoshort=名字太短
LID_nationalities=国籍
LID_nationality=国籍
LID_ndsweps=不可丢弃武器(无法丢弃)
LID_network=网络
LID_new=新
LID_news=新闻
LID_newyourrpversionavailable=新版本 %yrp% 可用
LID_next=下一个
LID_nextvoicechannel=下一个语音频道
LID_nick=昵称
LID_no=否
LID_nogroupspawn=无群组出生点
LID_noisy=喧闹
LID_nojailpoint=无监狱点
LID_none=无
LID_noreleasepoint=无释放点
LID_normal=正常
LID_north=北
LID_north_short=北
LID_noslot=无槽位
LID_notadded=未添加
LID_notallowed=不允许
LID_note=备注
LID_notequipment=非装备
LID_notes=备注
LID_notrequired=非必需
LID_npc=NPC
LID_npcs=NPC
LID_npcspawner=NPC生成器
LID_numpadhome=Home键
LID_off=关闭
LID_ok=确定
LID_on=开启
LID_oncooldown=冷却中
LID_onlyfaction=仅限阵营
LID_onlygroup=仅限群组
LID_onlyrole=仅限角色
LID_ooc=性格失常
LID_openprofile=打开个人资料
LID_opensteamprofile=打开steam资料
LID_operatingsystem=操作系统
LID_os=OS系统
LID_os_linux=Linux系统
LID_os_osx=OSX系统
LID_os_other=其他OS系统
LID_os_windows=Win系统
LID_other=其他
LID_othermodels=其他模型
LID_owned=已拥有
LID_owner=所有者
LID_page=页面
LID_passive=被动
LID_password=密码
LID_percent=百分比
LID_percentage=百分比
LID_performance=性能
LID_permanent=永久
LID_permille=千分比
LID_ping=延迟
LID_placehit=发布悬赏
LID_play=播放
LID_playbutton=播放按钮
LID_player=玩家
LID_playermodel=玩家模型
LID_playermodels=玩家模型
LID_players=玩家
LID_playtime=玩游戏的时间
LID_pleasewait=请稍候
LID_pointto=指向
LID_port=端口
LID_pose=姿势
LID_poses=姿势
LID_position=位置
LID_possiblesweps=可用武器
LID_prefix=前缀
LID_press=按下
LID_pressed=已按下
LID_presskeytoenablevoicemenu=按 [KEY] 启用语音菜单
LID_presstochangeyourclothes=按 %KEY% 更换你的衣服
LID_presstoclosesmartphone=按下来关闭智能手机
LID_presstogetin=按 %KEY% 上车
LID_presstogetout=按 %KEY% 下车
LID_presstointeractwith=按 %KEY% 与 %NAME% 互动
LID_presstoopen=按 %KEY% 打开
LID_presstoopensettings=按 %KEY% 打开设置
LID_presstoopensmartphone=按下来打开智能手机
LID_presstotrade=按 %KEY% 交易
LID_pressvoicetoopenradiomenu=按 [KEY] 打开对讲机菜单
LID_prev=上一个
LID_previousvoicechannel=上一个语音频道
LID_price=价格
LID_primary=主要
LID_primaryslot=主武器槽
LID_primaryslots=主武器槽
LID_printer=打印机
LID_prisoners=囚犯
LID_problems=问题
LID_profile=个人资料
LID_profiles=个人资料
LID_prop=道具
LID_props=道具
LID_public=公开
LID_quantity=数量
LID_queryport=查询端口
LID_quiet=安静
LID_quit=退出
LID_radiation=辐射
LID_radiodisabled=对讲机已禁用
LID_ragdoll=布娃娃
LID_rage=怒气
LID_range=范围
LID_rank=等级
LID_ranks=等级
LID_ready=准备就绪
LID_reason=原因
LID_receiveserverdata=接收服务器数据
LID_records=记录
LID_remove=删除
LID_removeall=全部移除
LID_removed=已移除
LID_removeentry=移除条目
LID_removeondeath=死亡时移除
LID_removeowner=移除所有者
LID_repair=修理
LID_report=举报
LID_require=需要
LID_required=必需
LID_requires=需要
LID_reset=重置
LID_respawn=重生
LID_respawned=已重生
LID_respawning=正在重生
LID_respawnnow=立即重生
LID_respawntime=重生时间
LID_restriction=限制
LID_restrictions=限制
LID_retryinxsec=%SECONDS% 秒后重试
LID_return=返回
LID_revive=复活
LID_reward=奖励
LID_rightclicktoshowmouse=右键点击以显示鼠标
LID_role=角色
LID_rolelogo=角色标志
LID_rolemenu=角色菜单
LID_roleplay=角色扮演
LID_roles=角色
LID_rolled=%NAME% 掷出: %NUMBER%
LID_rotate=旋转
LID_rpname=角色名字
LID_safezone=安全区
LID_salary=薪水
LID_salute=敬礼
LID_save=保存
LID_savebodygroups=保存人物模型分组
LID_say=说
LID_scale=比例
LID_scoreboard=计分板
LID_search=搜索
LID_searching=正在搜索
LID_second=秒
LID_secondary=次要
LID_secondaryslot=次武器槽
LID_secondaryslots=次武器槽
LID_seconds=秒
LID_securitylevel=安全等级
LID_securitylevelsystem=安全等级系统
LID_sell=出售
LID_send=发送
LID_sendclientinfo=发送客户端信息
LID_sendfeedback=发送反馈
LID_sendticket=发送工单
LID_server=服务器
LID_server_console=服务器控制台
LID_serverid=服务器ID
LID_servers=服务器
LID_serveruptime=服务器运行时间
LID_service=服务
LID_setasserverdefault=设为服务器默认
LID_settodefault=设置默认
LID_shop=商店
LID_showchanges=显示更新内容
LID_showidcardid=显示身份证ID
LID_showowner=显示所有者
LID_sidearm=副武器
LID_sidearms=副武器
LID_sidearmslot=副武器槽
LID_sidearmslots=副武器槽
LID_simple=简单
LID_siteisloading=网站正在加载
LID_slap=拍打
LID_slay=击杀
LID_someonehasjoinedthefrequency=有人加入了该频道
LID_someonehasleftthefrequency=有人离开了该频道
LID_south=南
LID_south_short=南
LID_spawn=出生点
LID_spawns=出生点
LID_speakfaction=阵营语音
LID_speakglobal=全局语音
LID_speakgroup=群组语音
LID_speaking=正在说话
LID_speaklocal=本地语音
LID_specializations=专精
LID_spectate=观战
LID_spectating=正在观战
LID_spirit=精神
LID_splint=夹板
LID_splinting=正在上夹板
LID_sqlmode=SQLITE数据库
LID_staff=工作人员
LID_standing=站立
LID_startlevel=初始等级
LID_stats=属性
LID_status=状态
LID_steamname=steam名字
LID_steamprofile=steam资料
LID_stomach=身
LID_storage=仓库
LID_storagepoint=存储点
LID_strength=力量
LID_structure=结构
LID_submit=提交
LID_suffix=后缀
LID_suggestions=建议
LID_suicide=自杀
LID_surrender=投降
LID_surrenderbehind=投降(背手)
LID_swep=武器 (SWEP)
LID_sweps=武器 (SWEP)
LID_swepsatspawn=出生时携带武器
LID_switchview=切换视图
LID_syringe=注射器
LID_tab=标签
LID_tabs=标签
LID_talent=天赋
LID_talents=天赋
LID_target=目标
LID_teleporter=传送器
LID_text=文本
LID_thecollectionidismissing=缺少CollectionID
LID_thickness=粗细
LID_thinking=正在思考
LID_thirsty=口渴
LID_ticket=工单
LID_tickets=工单
LID_ticketsmenu=工单菜单
LID_tieup=绑起来
LID_time=时间
LID_timeinhou=时间(小时)
LID_timeinmin=时间(分钟)
LID_timeinsec=时间(秒)
LID_title=标题
LID_to=到
LID_toggle=切换
LID_togglemouse=光标 开/关
LID_tool=工具
LID_tools=工具
LID_totaluptime=总运行时间
LID_tpp=第三人称
LID_tpto=传送至
LID_trade=交易
LID_trading=正在交易
LID_translator=翻译者
LID_turnviewingangletotheleft=转视角向左
LID_turnviewingangletotheright=转视角向右
LID_type=类型
LID_typing=正在打字
LID_unarmed=放下武器
LID_unassigned=未分配
LID_unblind=解除致盲
LID_uncloak=取消隐身
LID_unfreeze=解冻
LID_ungod=关闭无敌模式
LID_unjail=释放
LID_unleash=释放
LID_unlock=未上锁
LID_unlocked=未上锁
LID_unlockeddoor=门已解锁
LID_unlockedvehicle=车辆已解锁
LID_unlocking=解锁中
LID_unragdoll=站起
LID_updateserver=更新服务器
LID_upgrade=升级
LID_use=使用
LID_user=用户
LID_usergroup=用户组
LID_usergroups=用户组
LID_username=用户名
LID_value=数值
LID_vehicle=车辆
LID_vehicles=车辆
LID_viewingangle=视角角度
LID_viewingheight=视角高度
LID_viewingposition=视角位置
LID_viewingpositiontotheleft=观看位置向左
LID_viewingpositiontotheright=观看位置向右
LID_violation=违规
LID_violations=违规
LID_visibility=可见性
LID_visible=显示
LID_voice=语音
LID_voicechat=语音聊天
LID_voicechatisdisabled=语音聊天已禁用
LID_voicechatradio=语音对讲机
LID_voicemodule=语音模块(右下角)
LID_voicerangedn=减少语音范围
LID_voicerangeup=增加语音范围
LID_wantstherole=%NAME% 想要角色 %ROLE%
LID_warning=警告
LID_warnings=警告
LID_weapon=武器
LID_weaponchest=武器箱
LID_weaponlowered=放下武器
LID_weaponlowering=放下武器
LID_weapons=武器
LID_weight=体重
LID_welcome=欢迎
LID_welcomeagentx=欢迎特工 %NAME%
LID_west=西
LID_west_short=西
LID_whisper=低语
LID_whitelist=白名单
LID_width=宽度
LID_wip=正在进行中的工作
LID_workshopversion=创意工坊版本
LID_xactive=X个激活
LID_xchannelactive=X个激活频道
LID_xchannelpassive=X个被动频道
LID_xpassive=X个被动
LID_xpforlevelup=升级所需经验
LID_xpoint=%VALUE% 点
LID_xpoints=%VALUE% 点
LID_xpperkill=每次击杀经验
LID_xpperminute=每分钟经验
LID_xpperrevive=每次复活经验
LID_year=年
LID_years=年
LID_yell=大喊
LID_yes=是
LID_you=你
LID_youarebleeding=你正在流血
LID_youarenotwhitelisted=你不在白名单中
LID_youarespeaking=你正在说话
LID_youareusing32bit=你正在使用32位GMod，请使用64位GMod
LID_youdied=你死亡了
LID_youdonthaveakey=你没有这个的钥匙
LID_youredeadinxseconds=你将在 %X% 秒后死亡
LID_youreunconsious=你已昏迷
LID_yourleftarmisbroken=你的左臂骨折了
LID_yourleftlegisbroken=你的左腿骨折了
LID_yourrightarmisbroken=你的右臂骨折了
LID_yourrightlegisbroken=你的右腿骨折了
LID_youwereinvited=你被邀请了
LID_zone=区域
