# not empty
LID_wip=開發中
LID_new=新
LID_roleplay=角色扮演
LID_usergroup=使用者群組
LID_usergroups=使用者群組
LID_rank=階級
LID_ranks=階級
LID_restriction=限制
LID_restrictions=限制
LID_givefeedback=提供意見回饋
LID_getlivesupport=取得即時支援
LID_icon=圖示
LID_logo=標誌
LID_weapon=武器
LID_weapons=武器
LID_entity=實體
LID_entities=實體
LID_prop=道具
LID_props=道具
LID_rpname=角色扮演名稱
LID_steamname=Steam名稱
LID_name=名稱
LID_nick=暱稱
LID_steamprofile=Steam個人檔案
LID_opensteamprofile=開啟Steam個人檔案
LID_username=使用者名稱
LID_password=密碼
LID_ip=IP
LID_hostname=主機名稱
LID_port=連接埠
LID_queryport=查詢連接埠
LID_serverid=伺服器ID
LID_database=資料庫
LID_sqlmode=SQL模式
LID_staff=管理團隊
LID_community=社群
LID_server=伺服器
LID_servers=伺服器
LID_news=新聞
LID_changelog=更新日誌
LID_role=職業
LID_roles=職業
LID_group=群組
LID_groups=群組
LID_ping=Ping
LID_frag=擊殺
LID_frags=擊殺數
LID_death=死亡
LID_deaths=死亡數
LID_playtime=遊玩時間
LID_key=按鍵
LID_keys=按鍵
LID_handcuffs=手銬
LID_handcuffed=已上銬
LID_bandage=繃帶
LID_bandages=繃帶
LID_arreststick=警棍
LID_unarmed=徒手
LID_player=玩家
LID_players=玩家
LID_map=地圖
LID_maps=地圖
LID_help=幫助
LID_helpmenu=幫助選單
LID_characterselection=角色選擇
LID_togglemouse=開啟/關閉滑鼠
LID_rolemenu=職業選單
LID_buymenu=購買選單
LID_inventory=背包
LID_appearance=外觀
LID_emote=表情動作
LID_emotes=表情動作
LID_drop=丟棄
LID_dropitem=丟棄物品
LID_dropweapon=丟棄武器
LID_weaponlowering=放低武器
LID_switchview=切換視角
LID_increaseviewingheight=提高視角高度
LID_decreaseviewingheight=降低視角高度
LID_viewingpositiontotheright=視角位置向右
LID_viewingpositiontotheleft=視角位置向左
LID_turnviewingangletotheright=視角角度向右轉
LID_turnviewingangletotheleft=視角角度向左轉
LID_holdtozoomoutview=按住以縮小視角
LID_holdtozoominview=按住以放大視角
LID_presstoopensmartphone=按下以開啟智慧型手機
LID_presstoclosesmartphone=按下以關閉智慧型手機
LID_nextvoicechannel=下一個語音頻道
LID_previousvoicechannel=上一個語音頻道
LID_weaponlowered=武器已放低
LID_suicide=自殺
LID_enterworld=進入世界
LID_title=標題
LID_collection=收藏
LID_moreinformation=更多資訊
LID_getrole=取得職業
LID_description=描述
LID_equipment=裝備
LID_notequipment=非裝備
LID_salary=薪水
LID_money=金錢
LID_health=生命值
LID_armor=護甲
LID_gender=性別
LID_gendermale=男性
LID_genderfemale=女性
LID_genderother=其他性別
LID_nameistoshort=名稱太短
LID_nameistolong=名稱太長
LID_back=返回
LID_add=新增
LID_remove=移除
LID_removeall=全部移除
LID_delete=刪除
LID_owner=擁有者
LID_coowner=共同擁有者
LID_coowners=共同擁有者
LID_you=你
LID_disabled=已停用
LID_enabled=已啟用
LID_enable=啟用
LID_disable=停用
LID_operatingsystem=作業系統
LID_os=作業系統
LID_os_windows=Windows
LID_os_linux=Linux
LID_os_osx=OSX
LID_os_other=其他作業系統
LID_motd=每日訊息
LID_damage=傷害
LID_damaged=已受損
LID_head=頭部
LID_chest=胸部
LID_stomach=腹部
LID_arms=手臂
LID_legs=腿部
LID_vehicle=載具
LID_vehicles=載具
LID_percentage=百分比
LID_percent=百分比
LID_multiplier=倍率
LID_empty=空的
LID_settodefault=設為預設值
LID_loading=載入中
LID_loadingdata=載入資料中
LID_connect=連線
LID_connecting=連線中
LID_connected=已連線
LID_disconnect=斷線
LID_disconnecting=斷線中
LID_disconnected=已斷線
LID_general=一般
LID_color=顏色
LID_colors=顏色
LID_icons=圖示
LID_change=變更
LID_changed=已變更
LID_locked=已上鎖
LID_unlocked=已解鎖
LID_lock=上鎖
LID_unlock=解鎖
LID_locking=上鎖中
LID_unlocking=解鎖中
LID_visible=可見
LID_hided=已隱藏
LID_hide=隱藏
LID_administrator=管理員
LID_admin=管理員
LID_user=使用者
LID_advert=廣播
LID_emotion=情緒
LID_looc=本地場外交流
LID_ooc=場外交流
LID_say=說話
LID_yell=大喊
LID_service=服務
LID_none=無
LID_stats=數據
LID_attribute=屬性
LID_attributes=屬性
LID_identitycard=身分證
LID_card=卡片
LID_faction=陣營
LID_factions=陣營
LID_simple=簡易
LID_advanced=進階
LID_scoreboard=計分板
LID_menu=選單
LID_menus=選單
LID_level=等級
LID_levelx=等級 %LEVEL%
LID_levelsystem=等級系統
LID_minimumlevel=最低等級
LID_maximumlevel=最高等級
LID_xpforlevelup=升級所需經驗值
LID_startlevel=起始等級
LID_xpperkill=每次擊殺經驗值
LID_xpperminute=每分鐘經驗值
LID_xpperrevive=每次復活經驗值
LID_levelup=升級
LID_keynumpad=數字鍵盤
LID_keypage=換頁鍵
LID_identifycard=識別證
LID_swep=SWEP
LID_sweps=SWEPs
LID_feedback=意見回饋
LID_problems=問題
LID_suggestions=建議
LID_contact=聯絡
LID_notrequired=非必要
LID_required=必要
LID_requires=需要
LID_require=需要
LID_sendfeedback=傳送意見回饋
LID_playermodel=玩家模型
LID_playermodels=玩家模型
LID_npc=NPC
LID_npcs=NPCs
LID_tab=分頁
LID_tabs=分頁
LID_buy=購買
LID_in_use=使用
LID_removeowner=移除擁有者
LID_building=建築
LID_buildings=建築
LID_price=價格
LID_door=門
LID_doors=門
LID_numpadhome=Home鍵
LID_keyinsert=Insert鍵
LID_fppr=寫實第一人稱
LID_fpp=第一人稱
LID_tpp=第三人稱
LID_viewingheight=視角高度
LID_viewingposition=視角位置
LID_viewingangle=視角角度
LID_youarespeaking=你正在說話
LID_voice=語音
LID_voicechat=語音聊天
LID_voicechatisdisabled=語音聊天已停用
LID_speakgroup=群組語音
LID_speakglobal=全域語音
LID_speaklocal=本地語音
LID_speakfaction=陣營語音
LID_youarebleeding=你正在流血
LID_cuffed=已上銬
LID_hungry=飢餓
LID_thirsty=口渴
LID_yourrightlegisbroken=你的右腿骨折了
LID_yourleftlegisbroken=你的左腿骨折了
LID_yourrightarmisbroken=你的右臂骨折了
LID_yourleftarmisbroken=你的左臂骨折了
LID_jail=監獄
LID_loaded=已載入
LID_dead=已死亡
LID_respawning=重生中
LID_respawned=已重生
LID_respawn=重生
LID_adminnotification=管理員通知
LID_noreleasepoint=沒有釋放點
LID_nojailpoint=沒有監獄點
LID_nogroupspawn=沒有群組重生點
LID_ndsweps=無法丟棄的SWEPs(無法丟棄)
LID_confirm=確認
LID_presstoopen=按下 %KEY% 開啟
LID_presstoopensettings=按下 %KEY% 開啟設定
LID_presstogetin=按下 %KEY% 上車
LID_presstogetout=按下 %KEY% 下車
LID_client=客戶端
LID_clients=客戶端
LID_about=關於
LID_showchanges=顯示變更
LID_newyourrpversionavailable=有新的 %yrp% 版本可用
LID_currentversion=目前版本
LID_workshopversion=創意工坊版本
LID_githubversion=Github版本
LID_downloadlatestversion=下載最新版本
LID_all=全部
LID_whitelist=白名單
LID_addentry=新增項目
LID_removeentry=移除項目
LID_dealer=經銷商
LID_dealers=經銷商
LID_storagepoint=儲存點
LID_storage=儲存空間
LID_quantity=數量
LID_cooldown=冷卻時間
LID_license=執照
LID_licenses=執照
LID_permanent=永久
LID_me=我
LID_second=秒
LID_seconds=秒
LID_minute=分鐘
LID_minutes=分鐘
LID_hour=小時
LID_hours=小時
LID_clock=時鐘
LID_day=天
LID_days=天
LID_month=月
LID_months=月
LID_year=年
LID_years=年
LID_siteisloading=網站載入中
LID_isloading=載入中
LID_type=類型
LID_search=搜尋
LID_searching=搜尋中
LID_next=下一個
LID_prev=上一個
LID_ok=確定
LID_cancel=取消
LID_yes=是
LID_no=否
LID_lockedvehicle=載具已上鎖
LID_unlockedvehicle=載具已解鎖
LID_lockeddoor=門已上鎖
LID_unlockeddoor=門已解鎖
LID_youdonthaveakey=你沒有這個的鑰匙
LID_position=位置
LID_angle=角度
LID_tpto=傳送至
LID_kick=踢除
LID_bring=傳喚
LID_ban=封鎖
LID_slay=擊殺
LID_slap=拍打
LID_ragdoll=布娃娃
LID_openprofile=開啟個人檔案
LID_god=無敵模式
LID_ignite=點燃
LID_freeze=凍結
LID_copysteamname=複製Steam名稱
LID_copysteamid=複製SteamID
LID_copysteamid64=複製SteamID64
LID_copyrpname=複製RP名稱
LID_blind=致盲
LID_cloak=隱形
LID_areyousure=你確定嗎?
LID_command=指令
LID_commands=指令
LID_backpack=背包
LID_hasbeendropped=%ITEM% 已被丟棄
LID_cannotbedropped=%ITEM% 無法被丟棄
LID_upgrade=升級
LID_printer=印表機
LID_off=關閉
LID_on=開啟
LID_money_printer=印鈔機
LID_max=最大值
LID_min=最小值
LID_gather=採集
LID_full=已滿
LID_fuelup=加油
LID_fuel=燃料
LID_cpu=CPU
LID_cooler=冷卻器
LID_serveruptime=伺服器運行時間
LID_currentuptime=目前運行時間
LID_totaluptime=總運行時間
LID_uncloak=解除隱形
LID_cloaked=已隱形
LID_unblind=解除致盲
LID_blinded=已致盲
LID_extinguish=熄滅
LID_unjail=釋放出獄
LID_ungod=解除無敵模式
LID_notallowed=不允許
LID_unassigned=未指派
LID_presstotrade=按下 %KEY% 進行交易
LID_presstointeractwith=按下 %KEY% 與 %NAME% 互動
LID_presstochangeyourclothes=按下 %KEY% 更換你的衣服
LID_hasfinishedloading=%NAME% 已完成載入
LID_globalchat=全域
LID_localchat=本地
LID_emotewave=揮手
LID_emotesalute=敬禮
LID_emotepers=嚇唬
LID_emotelaugh=大笑
LID_emotehalt=停止
LID_emoteimitiationzombie=模仿殭屍
LID_emotegroup=集合
LID_emoteforward=前進
LID_emotedisagree=不同意
LID_emotedancesexy=性感舞蹈
LID_emotedancerobot=機器人舞
LID_emotedancenormal=一般舞蹈
LID_emotecheer=歡呼
LID_emotebecon=招手示意
LID_emotebow=鞠躬
LID_emoteagree=同意
LID_light=淺色
LID_dark=深色
LID_length=長度
LID_gap=間距
LID_thickness=厚度
LID_border=邊框
LID_width=寬度
LID_height=高度
LID_close=關閉
LID_exit=離開
LID_trade=交易
LID_trading=交易中
LID_afk=離開
LID_dnd=請勿打擾
LID_give=給予
LID_wantstherole=%NAME% 想要職業 %ROLE%
LID_frozen=已凍結
LID_unfreeze=解除凍結
LID_unragdoll=解除布娃娃
LID_deleteentry=刪除項目
LID_rolled=%NAME% 擲出了: %NUMBER%
LID_welcome=歡迎
LID_other=其他
LID_model=模型
LID_models=模型
LID_othermodels=其他模型
LID_updateserver=更新伺服器
LID_page=頁面
LID_toggle=切換
LID_added=已新增
LID_notadded=未新增
LID_removed=已移除
LID_sell=出售
LID_hud=HUD
LID_customize=自訂
LID_done=完成
LID_chat=聊天
LID_visibility=可見度
LID_background=背景
LID_text=文字
LID_minimap=小地圖
LID_performance=效能
LID_compass=指南針
LID_fps=FPS
LID_network=網路
LID_north=北
LID_south=南
LID_east=東
LID_west=西
LID_north_short=北
LID_south_short=南
LID_east_short=東
LID_west_short=西
LID_access=存取權限
LID_minimumsize=最小尺寸
LID_maximumsize=最大尺寸
LID_language=語言
LID_languages=語言
LID_country=國家
LID_contries=國家
LID_law=法律
LID_laws=法律
LID_lawsymbol=法律符號
LID_hover=懸停
LID_hoverover=滑鼠懸停於
LID_hovered=已懸停
LID_press=按下
LID_pressed=已按下
LID_server_console=伺服器主控台
LID_pleasewait=請稍候
LID_iamstuck=我卡住了
LID_send=傳送
LID_submit=提交
LID_lockdown=封鎖
LID_lockdowntext=封鎖文字
LID_reason=原因
LID_lockpick=開鎖器
LID_lockpicking=開鎖中
LID_syringe=針筒
LID_splint=夾板
LID_food=食物
LID_drink=飲料
LID_eating=進食中
LID_drinking=飲用中
LID_repair=修理
LID_batteringram=破門錘
LID_time=時間
LID_timeinsec=時間(秒)
LID_timeinmin=時間(分鐘)
LID_timeinhou=時間(小時)
LID_becomerole=成為該職業
LID_distance=距離
LID_forcesetkeybinds=強制設定按鍵綁定
LID_setasserverdefault=設為伺服器預設值
LID_reset=重設
LID_header=標頭
LID_canbeowned=可被擁有
LID_profile=個人檔案
LID_profiles=個人檔案
LID_lostconnection=連線中斷
LID_retryinxsec=%SECONDS% 秒後重試
LID_characterssettings=角色設定
LID_idcard=身分證
LID_idcardid=身分證ID
LID_showidcardid=顯示身分證ID
LID_idstructure=ID結構
LID_grouplogo=群組標誌
LID_rolelogo=職業標誌
LID_securitylevel=安全等級
LID_public=公開
LID_npcspawner=NPC生成器
LID_respawntime=重生時間
LID_adminonly=僅限管理員
LID_custom=自訂
LID_namechangeable=名稱可更改
LID_id=ID
LID_force=強制
LID_mana=法力值
LID_rage=怒氣值
LID_energy=能量
LID_ability=能力
LID_warning=警告
LID_warnings=警告
LID_violation=違規
LID_violations=違規
LID_unleash=釋放
LID_tieup=綑綁
LID_voicechatradio=語音對講機
LID_someonehasjoinedthefrequency=有人加入了頻率
LID_someonehasleftthefrequency=有人離開了頻率
LID_iscp=是治安警察
LID_ismedic=是醫護人員
LID_ismayor=是市長
LID_splinting=上夾板中
LID_bandaging=包紮中
LID_target=目標
LID_cell=牢房
LID_prisoners=囚犯
LID_records=記錄
LID_note=備註
LID_notes=備註
LID_arrests=逮捕記錄
LID_arrest=逮捕
LID_youdied=你死亡了
LID_changecharacter=更換角色
LID_respawnnow=立即重生
LID_youreunconsious=你已昏迷
LID_youredeadinxseconds=你將在 %X% 秒後死亡
LID_revive=復活
LID_status=狀態
LID_manually=手動
LID_kill=擊殺
LID_kills=擊殺數
LID_connection=連線
LID_connections=連線
LID_spawn=生成
LID_spawns=生成點
LID_factor=係數
LID_scale=縮放
LID_changefaction=更換陣營
LID_radiation=輻射
LID_hygiene=衛生
LID_environment=環境
LID_bag=袋子
LID_value=數值
LID_mutevoice=靜音語音
LID_dashboard=儀表板
LID_shop=商店
LID_ticket=工單
LID_tickets=工單
LID_sendticket=傳送工單
LID_event=活動
LID_use=使用
LID_macromenu=巨集選單
LID_youarenotwhitelisted=你不在白名單中
LID_entspawner=實體生成器
LID_deathscreen=死亡畫面
LID_safezone=安全區
LID_birthday=生日
LID_bodyheight=身高
LID_weight=體重
LID_nationality=國籍
LID_nationalities=國籍
LID_welcomeagentx=歡迎探員 %NAME%
LID_accepthit=接受懸賞
LID_reward=獎勵
LID_createhit=建立懸賞
LID_placehit=發布懸賞
LID_active=主動
LID_passive=被動
LID_save=儲存
LID_edit=編輯
LID_it=它
LID_mode=模式
LID_structure=結構
LID_from=從
LID_to=到
LID_talents=天賦
LID_talent=天賦
LID_range=範圍
LID_voicerangeup=增加語音範圍
LID_voicerangedn=減少語音範圍
LID_whisper=低語
LID_quiet=安靜
LID_normal=正常
LID_noisy=吵雜
LID_strength=力量
LID_agility=敏捷
LID_intellect=智力
LID_spirit=精神
LID_xpoint=%VALUE% 點
LID_xpoints=%VALUE% 點
LID_tool=工具
LID_tools=工具
LID_permille=千分比
LID_item=物品
LID_items=物品
LID_category=類別
LID_categories=類別
LID_thecollectionidismissing=缺少收藏ID
LID_default=預設
LID_defaults=預設值
LID_hearq=聽到了嗎?
LID_oncooldown=冷卻中
LID_rightclicktoshowmouse=按右鍵顯示滑鼠
LID_ammo=彈藥
LID_ammunation=軍火商
LID_antipropkill=防道具卡死
LID_radiodisabled=對講機已停用
LID_1channelactive=1個啟用頻道
LID_xchannelactive=X個啟用頻道
LID_1channelpassive=1個被動頻道
LID_xchannelpassive=X個被動頻道
LID_1active=1個啟用
LID_1passive=1個被動
LID_xactive=X個啟用
LID_xpassive=X個被動
LID_pressvoicetoopenradiomenu=按下 [KEY] 開啟對講機選單
LID_join=加入
LID_leave=離開
LID_play=播放
LID_charactermenu=角色選單
LID_keybindsmenu=按鍵綁定選單
LID_ticketsmenu=工單選單
LID_removeondeath=死亡時移除
LID_playbutton=播放按鈕
LID_voicemodule=語音模組(右下角)
LID_showowner=顯示擁有者
LID_info=資訊
LID_information=資訊
LID_spectate=觀戰
LID_spectating=觀戰中
LID_account=帳號
LID_return=返回
LID_invitetogroup=邀請加入群組
LID_invitetofaction=邀請加入陣營
LID_invitation=邀請
LID_youwereinvited=你被邀請了
LID_accept=接受
LID_decline=拒絕
LID_pose=姿勢
LID_poses=姿勢
LID_pointto=指向
LID_crossarms=抱胸
LID_crossarmsbehind=抱胸(背後)
LID_salute=敬禮
LID_hololink=全息連結
LID_comlink=通訊器
LID_surrender=投降
LID_surrenderbehind=投降(背後)
LID_hip=臀部
LID_typing=輸入中
LID_speaking=說話中
LID_thinking=思考中
LID_drag=拖拽
LID_standing=站立
LID_kneeling=下跪
LID_possiblesweps=可能的SWEPs
LID_swepsatspawn=出生時的SWEPs
LID_primary=主要
LID_primaryslot=主要欄位
LID_primaryslots=主要欄位
LID_secondary=次要
LID_secondaryslot=次要欄位
LID_secondaryslots=次要欄位
LID_sidearm=副武器
LID_sidearms=副武器
LID_sidearmslot=副武器欄位
LID_sidearmslots=副武器欄位
LID_gadget=裝置
LID_gadgets=裝置
LID_gadgetslot=裝置欄位
LID_gadgetslots=裝置欄位
LID_weaponchest=武器箱
LID_noslot=無欄位
LID_equip=裝備
LID_coverears=摀住耳朵
LID_report=舉報
LID_middlefinger=比中指
LID_facepalm=摀臉
LID_specializations=專精
LID_displayname=顯示名稱
LID_prefix=前綴
LID_suffix=後綴
LID_automaticmapchangeinx=X後自動切換地圖
LID_zone=區域
LID_onlyfaction=僅限陣營
LID_onlygroup=僅限群組
LID_onlyrole=僅限職業
LID_entered=已進入
LID_adminmode=管理員模式
LID_ready=準備就緒
LID_presskeytoenablevoicemenu=按下 [KEY] 開啟語音選單
LID_maxactive=最大啟用數
LID_maxpassive=最大被動數
LID_logs_settings=記錄(設定)
LID_enteryourfirstname=輸入你的名字
LID_enteryoursurname=輸入你的姓氏
LID_identifier=識別碼
LID_gamemodedeveloper=遊戲模式開發者
LID_developer=開發者
LID_gamemodetranslator=遊戲模式翻譯者
LID_translator=翻譯者
LID_autopickup=自動拾取
LID_quit=離開
LID_createcharacter=創建角色
LID_rotate=旋轉
LID_create=創建
LID_import=匯入
LID_export=匯出
LID_loadingdesign=載入設計中
LID_savebodygroups=儲存身體部件
LID_logout=登出
LID_logouttime=登出時間
LID_youareusing32bit=你正在使用32位元的GMod,請使用64位元的GMod
LID_sendclientinfo=傳送客戶端資訊
LID_receiveserverdata=接收伺服器資料
LID_teleporter=傳送器
LID_member=成員
LID_members=成員
LID_owned=已擁有
LID_groupmenu=群組選單
LID_securitylevelsystem=安全等級系統
LID_allbuildingsunlocked=所有建築已解鎖
