LID_1active=1 Ativo
LID_1channelactive=1 Canal Ativo
LID_1channelpassive=1 Canal Passivo
LID_1passive=1 Passivo
# Ability (Rage, Energy, Force, Mana)
LID_ability=Habilidade
LID_about=Sobre
LID_accept=Aceitar
LID_accepthit=Aceitar Contrato
LID_access=Acesso
LID_account=Conta
LID_active=Ativo
LID_add=Adicionar
LID_added=Adicionado
LID_addentry=Adicionar entrada
LID_admin=Admin
LID_administrator=Administrador
LID_adminmode=Modo Admin
LID_adminnotification=Notificação de Admin
LID_adminonly=Administrador apenas
LID_advanced=Avançado
LID_advert=Advertir
LID_afk=AFK
LID_agility=Agilidade
LID_all=Tudo
LID_allbuildingsunlocked=Todos os Edifícios Desbloqueados
LID_ammo=Munição
LID_ammunation=Ammunation
LID_angle=Ângulo
LID_antipropkill=Anti Propkill
LID_appearance=Aparencia
LID_areyousure=Você tem certeza?
LID_armor=Armadura
LID_arms=Braços
LID_arrest=Prender
LID_arrests=Prisões
LID_arreststick=Bastão de prisão
LID_attribute=Atributo
LID_attributes=Atributos
LID_automaticmapchangeinx=Troca automática de mapa em X
LID_autopickup=Coleta Automática
LID_back=Voltar
LID_background=Fundo
LID_backpack=Mochila
LID_bag=Bolsa
LID_ban=Banir
LID_bandage=Bandage
LID_bandages=Bandages
LID_bandaging=Enfaixar
LID_batteringram=Aríete
LID_becomerole=Pegar cargo
LID_birthday=Aniversário
LID_blind=Cego
LID_blinded=Vendado
LID_bodyheight=Altura do Corpo
LID_border=Fronteira
LID_box=Caixa
LID_bring=Conduzir
LID_building=Construção
LID_buildings=Construções
LID_buy=Comprar
LID_buymenu=Menu de compra
LID_canbeowned=Pode ser possuído
LID_cancel=Cancelar
LID_cannotbedropped=%ITEM% não pode ser largado
LID_card=Cartão
LID_categories=Categorias
LID_category=Categoria
#jail cell
LID_cell=Cela
LID_change=Alterar
LID_changecharacter=Mudar Personagem
LID_changed=Alterado
LID_changefaction=Mudar facção
LID_changelog=Log de alterações
LID_charactermenu=Menu de Personagem
LID_characterselection=Seleção de personagem
LID_characterssettings=Configurações de personagem
LID_chat=Chat
LID_chest=Peitoral
LID_client=Cliente
LID_clients=Clientes
LID_cloak=Capa
LID_cloaked=Coberto
LID_clock=Relógio
LID_close=Fechar
LID_collection=Coleção
LID_color=Cor
LID_colors=Cores
LID_comlink=Comlink
LID_command=Comando
LID_commands=Comandos
LID_community=Comunidade
LID_compass=Bússola
LID_confirm=Confirmar
LID_connect=Conectar
LID_connected=Conectado
LID_connecting=Conectando
LID_connection=Conexão
LID_connections=Conexões
LID_contact=Contato
LID_contries=Países
LID_cooldown=Cooldown
LID_cooler=Cooler
LID_coowner=Co-Proprietário
LID_coowners=Co-Proprietários
LID_copyrpname=Copiar NomeRP
LID_copysteamid=Copiar SteamID
LID_copysteamid64=Copiar SteamID64
LID_copysteamname=Copiar Nome Steam
LID_country=País
LID_coverears=Cobrir Ouvidos
LID_cpu=CPU
LID_create=Criar
LID_createcharacter=Criar Personagem
LID_createhit=Criar Contrato
LID_crossarms=Cruzar Braços
LID_crossarmsbehind=Cruzar Braços (atrás)
LID_cuffed=Algemado
LID_currentuptime=Tempo atual do Servidor
LID_currentversion=Versão atual
#just custom, not specific one
LID_custom=Customizar
LID_customize=Customizar
LID_damage=Dano
LID_damaged=Estragado
LID_dark=Escuro
LID_dashboard=Painel
LID_database=Base de dados
LID_day=Dia
LID_days=Dias
LID_dead=Morto
LID_dealer=Negociante
LID_dealers=Negociadores
LID_death=Morte
LID_deaths=Mortes
LID_deathscreen=Tela de Morte
LID_decline=Recusar
LID_decreaseviewingheight=Diminua a altura de visualização
LID_default=Padrão
LID_defaults=Padrões
LID_delete=Deletar
LID_deleteentry=Apagar entrada
LID_description=Descrição
LID_developer=Desenvolvedor
LID_disable=Desabilitar
LID_disabled=Desabilitado
LID_disconnect=Desconectar
LID_disconnected=Desconectado
LID_disconnecting=Desconectando
LID_displayname=Nome de Exibição
LID_distance=Distância
LID_dnd=NP
LID_done=Feito
LID_door=Porta
LID_doors=Portas
LID_downloadlatestversion=Baixar ultima versão
LID_drag=Arrastar
LID_drink=Bebida
LID_drinking=Bebendo
LID_drop=Largar
LID_dropitem=Largar item
LID_dropweapon=Largar arma
LID_east=Leste
#East
LID_east_short=L
LID_eating=Comendo
LID_edit=Editar
LID_emote=Emote
LID_emoteagree=Concordar
LID_emotebecon=Acenar
LID_emotebow=Arco
LID_emotecheer=Animar
LID_emotedancenormal=Dança Normal
LID_emotedancerobot=Dança Robo
LID_emotedancesexy=Dança Sexy
LID_emotedisagree=Descordar
LID_emoteforward=Frente
LID_emotegroup=Agrupar
LID_emotehalt=Parado
LID_emoteimitiationzombie=Imitar Zumbi
LID_emotelaugh=Rir
LID_emotepers=Assustar
LID_emotes=Emotes
LID_emotesalute=Saudação
LID_emotewave=Onda
LID_emotion=Emoção
LID_empty=Vazio
LID_enable=Habilitar
LID_enabled=Habilitado
#Energy from Warcraft
LID_energy=Energia
LID_entered=Entrou
LID_enterworld=Entrar no mundo
LID_enteryourfirstname=Digite seu Primeiro nome
LID_enteryoursurname=Digite seu Sobrenome
LID_entities=Entidades
LID_entity=Entidade
LID_entspawner=Spawner de Entidades
LID_environment=Ambiente
LID_equip=Equipar
LID_equipment=Equipamento
LID_event=Evento
LID_exit=Sair
LID_export=Exportar
LID_extinguish=Extinguir
LID_extra=Extra
LID_facepalm=Facepalm
LID_faction=Facção
LID_factions=Facções
LID_factor=Fator
LID_feedback=Feedback
LID_food=Comida
#force from starwars
LID_force=Força
LID_forcesetkeybinds=Forçar atribuição de teclas
LID_fpp=Primeira pessoa
LID_fppr=Primeira pessoa Realista
#FramePerSecond => FPS
LID_fps=FPS
LID_frag=Frag
LID_frags=Frags
LID_freeze=Congelar
LID_from=De
LID_frozen=Congelado
LID_fuel=Combustível
LID_fuelup=Abastecer
LID_full=Cheio
LID_gadget=Gadget
LID_gadgets=Gadgets
LID_gadgetslot=Slot de Gadget
LID_gadgetslots=Slots de Gadget
LID_gamemodedeveloper=Desenvolvedor do Gamemode
LID_gamemodetranslator=Tradutor do Gamemode
LID_gap=Lacuna
LID_gather=Coletar
LID_gender=Gênero
LID_genderfemale=Feminino
LID_gendermale=Masculino
LID_genderother=Outro gênero
LID_general=Geral
LID_getlivesupport=Obter suporte Instantâneo
LID_getrole=Pegar cargo
LID_githubversion=Versão do Github
LID_give=Pegar
LID_givefeedback=De sua opinião
LID_globalchat=Global
LID_god=Deus
LID_group=Grupo
LID_grouplogo=Logo de grupo
LID_groupmenu=Menu de Grupo
LID_groups=Grupos
LID_handcuffed=Algemado
LID_handcuffs=Algemas
LID_hasbeendropped=%ITEM% foi largado
LID_hasfinishedloading=%NAME% terminou de carregar
LID_head=Cabeça
LID_header=Cabeçalho
LID_health=Vida
LID_hearq=Ouvir?
LID_height=Altura
LID_help=Ajuda
LID_helpmenu=Menu de ajuda
LID_hide=Esconder
LID_hided=Escondido
LID_hip=Quadril
LID_holdtozoominview=Segure para aumentar o zoom
LID_holdtozoomoutview=Segure para reduzir o zoom
LID_hololink=Hololink
LID_hostname=Nome Host
LID_hour=Hora
LID_hours=Horas
#to hover (verb)
LID_hover=Pairar
LID_hovered=Pairado
LID_hoverover=Pairar sobre
LID_hud=HUD
LID_hungry=Com fome
LID_hygiene=Higiene
LID_iamstuck=Estou preso
LID_icon=Icone
LID_icons=Ícones
#just id, not idcard
LID_id=ID
LID_idcard=RG
LID_idcardid=RGID
LID_identifier=Identificador
LID_identifycard=Cartão de identificação
LID_identitycard=carteira de identidade
LID_idstructure=Estrutura de identificação
LID_ignite=Ignição
LID_import=Importar
LID_in_use=Usar
LID_increaseviewingheight=Aumentar a altura de visualização
LID_info=Info
LID_information=Informação
LID_intellect=Intelecto
LID_inventory=Inventario
LID_invitation=Convite
LID_invitetofaction=Convidar para a Facção
LID_invitetogroup=Convidar para o Grupo
LID_ip=IP
LID_iscp=Proteção Civil
LID_isloading=Carregando
LID_ismayor=É prefeito
LID_ismedic=É Médico
LID_it=Isso
LID_item=Item
LID_items=Itens
LID_jail=Cadeia
LID_join=Entrar
LID_key=Chave
LID_keybindsmenu=Menu de Atalhos
#Keyboard key [Insert]
LID_keyinsert=Insert
LID_keynumpad=Numpad
LID_keypage=Página
LID_keys=Chaves
LID_kick=Chute
LID_kill=Morte
LID_kills=Mortes
LID_kneeling=Ajoelhar
LID_language=Língua
LID_languages=Línguas
LID_law=Lei
LID_laws=Leis
LID_lawsymbol=Símbolo da lei
LID_leave=Sair
LID_legs=Pernas
LID_length=Tamanho
LID_level=Nível
LID_levels=Níveis
#Level system (settings)
LID_levelsystem=Sistema de níveis
LID_levelup=Novo nivel
#Level 1
LID_levelx=Nivel %LEVEL%
LID_license=Licença
LID_licenses=Licenças
LID_light=Claro
LID_loaded=Carregado
LID_loading=Carregando
LID_loadingdata=Carregando Dados
LID_loadingdesign=Carregando Design
LID_localchat=Local
LID_lock=Travar
LID_lockdown=Bloqueio
LID_lockdowntext=Texto de bloqueio
LID_locked=Travado
LID_lockeddoor=Porta trancada
LID_lockedvehicle=Veículo trancado
LID_locking=Travando
LID_lockpick=Travar
LID_lockpicking=Travando
LID_logo=Logo
LID_logout=Sair da Conta
LID_logouttime=Tempo de Logout
LID_logs_settings=Logs (Configurações)
LID_looc=Local ao redor
LID_lostconnection=Conexão Perdida
LID_macromenu=Menu de Macros
LID_mana=Mana
LID_manually=Manualmente
LID_map=Mapa
LID_maps=Mapas
LID_max=Max
LID_maxactive=Máximo Ativos
LID_maximumlevel=Nível máximo
LID_maximumsize=Tamanho máximo
LID_maxpassive=Máximo Passivos
LID_me=Eu
LID_member=Membro
LID_members=Membros
LID_menu=Menu
LID_menus=Menus
LID_middlefinger=Dedo do Meio
LID_min=Min
LID_minimap=Minimapa
LID_minimumlevel=Nível mínimo
LID_minimumsize=Tamanho mínimo
LID_minute=Minuto
LID_minutes=Minutos
LID_mode=Modo
LID_model=Modelo
LID_models=Modelos
LID_money=Dinheiro
LID_money_printer=Impressora de dinheiro
LID_month=Mês
LID_months=Meses
LID_moreinformation=Mais informações
LID_motd=MOTD
LID_multiplier=Multiplicador
LID_mutevoice=Mutar voz
LID_name=Nome
LID_namechangeable=O nome é alterável
LID_nameistolong=O nome é muito longo
LID_nameistoshort=O nome é muito curto
LID_nationalities=Nacionalidades
LID_nationality=Nacionalidade
LID_ndsweps=SWEPs não largáveis
#Network
LID_network=Rede
LID_new=Novo
LID_news=Noticias
LID_newyourrpversionavailable=%yrp% Tem uma nova versão disponível
LID_next=Próximo
LID_nextvoicechannel=Próximo canal de voz
LID_nick=Apelido
LID_no=Não
LID_nogroupspawn=Sem grupo de ponto de spawn
LID_noisy=Alto
LID_nojailpoint=Sem ponto de cadeia
LID_none=Nenhum
LID_noreleasepoint=Nenhum ponto de renascimento
LID_normal=Normal
LID_north=Norte
#North
LID_north_short=N
LID_noslot=Sem Slot
LID_notadded=Não adicionado
LID_notallowed=Não permitido
LID_note=Nota
LID_notequipment=NÃO Equipamento
LID_notes=Notas
LID_notrequired=Não requerido
LID_npc=NPC
LID_npcs=NPCs
LID_npcspawner=NPC spawner
LID_numpadhome=Casa
LID_off=Off
LID_ok=Ok
LID_on=On
LID_oncooldown=Em Recarga
LID_onlyfaction=Apenas Facção
LID_onlygroup=Apenas Grupo
LID_onlyrole=Apenas Cargo
LID_ooc=livre
LID_openprofile=Abrir Perfil
LID_opensteamprofile=Abrir Perfil Steam
LID_operatingsystem=Sistema Operacional
LID_os=OS
LID_os_linux=Linux
LID_os_osx=OSX
LID_os_other=Outro SO
LID_os_windows=Windows
LID_other=Outro
LID_othermodels=Outros Modelos
LID_owned=Possuído
LID_owner=Dono
LID_page=Página
LID_passive=Passivo
LID_password=Senha
LID_percent=Por cento
LID_percentage=Percentagem
LID_performance=Atuação
LID_permanent=Permanente
LID_permille=Por mil
LID_ping=Ping
LID_placehit=Colocar Contrato
LID_play=Jogar
LID_playbutton=Botão Jogar
LID_player=Jogador
LID_playermodel=Playermodel
LID_playermodels=Playermodels
LID_players=Jogadores
LID_playtime=Tempo de jogo
LID_pleasewait=Por favor, espere
LID_point=Ponto
LID_points=Pontos
LID_pointto=Apontar para
LID_port=Porta
LID_pose=Pose
LID_poses=Poses
LID_position=Posição
LID_possiblesweps=SWEPs Possíveis
LID_prefix=Prefixo
#to press (verb)
LID_press=Pressione
LID_pressed=Pressionado
LID_presskeytoenablevoicemenu=Pressione [KEY] para ativar o menu de voz
LID_presstochangeyourclothes=Pressione %KEY% para trocar suas roupas
LID_presstoclosesmartphone=pressione para fechar smartphone
LID_presstogetin=Pressione %KEY% para entrar
LID_presstogetout=Pressione %KEY% para sair
LID_presstointeractwith=Pressione %KEY% para interagir com %NAME%
LID_presstoopen=Pressione %KEY% para abrir
LID_presstoopensettings=Pressione %KEY% para abrir as configurações
LID_presstoopensmartphone=Pressione para abrir smartphone
LID_presstotrade=Pressione %KEY% para trocar
LID_pressvoicetoopenradiomenu=Pressione [KEY] para o menu de rádio
LID_prev=Anterior
LID_previousvoicechannel=Canal de voz anterior
LID_price=Preço
LID_primary=Primária
LID_primaryslot=Slot Primário
LID_primaryslots=Slots Primários
LID_printer=Impressora
LID_prisoners=Prisioneiros
LID_problems=Problemas
LID_profile=Perfil
LID_profiles=Perfis
LID_prop=Prop
LID_props=Props
#general public word
LID_public=Publico
LID_quantity=Quantidade
LID_queryport=Porta query
LID_quiet=Baixo
LID_quit=Sair
LID_radiation=Radiação
LID_radiodisabled=Rádio desativado
LID_ragdoll=Ragdoll
#Rage from Warcraft
LID_rage=Fúria
LID_range=Alcance
LID_rank=Patente
LID_ranks=Patentes
LID_ready=Pronto
LID_reason=Motivo
LID_receiveserverdata=Receber Dados do Servidor
LID_records=Registros
LID_remove=Remover
LID_removeall=Remover Tudo
LID_removed=Removido
LID_removeentry=Remover entrada
LID_removeondeath=Remover ao Morrer
LID_removeowner=Remover dono
LID_repair=Reparar
LID_report=Denunciar
LID_require=Pedir
LID_required=Requerido
LID_requires=Requer
LID_reset=Recomeçar
LID_respawn=Renascer
LID_respawned=Renascido
LID_respawning=Renascendo
LID_respawnnow=Nascer agora
LID_respawntime=Tempo de renascimento
LID_restriction=Restrição
LID_restrictions=Restrições
LID_retryinxsec=Tente novamente em: %SECONDS% segundos
LID_return=Retornar
LID_revive=Reviver
LID_reward=Recompensa
LID_rightclicktoshowmouse=Clique com o botão direito para mostrar o mouse
LID_role=Cargo
LID_rolelogo=Logo de cargo
LID_rolemenu=Menu de cargos
LID_roleplay=Roleplay
LID_roles=Cargos
LID_rolled=%NAME% Rolou: %NUMBER%
LID_rotate=Girar
LID_rpname=Nome Cargo
LID_safezone=Zona Segura
LID_salary=Salario
LID_salute=Saudar
LID_save=Salvar
LID_savebodygroups=Salvar Bodygroups
LID_say=Falar
LID_scale=Escala
LID_scoreboard=Placar
LID_search=Procurar
LID_searching=Procurando
LID_second=Segundo
LID_secondary=Secundária
LID_secondaryslot=Slot Secundário
LID_secondaryslots=Slots Secundários
LID_seconds=Segundos
LID_securitylevel=Nível de segurança
LID_securitylevelsystem=Sistema de Nível de Segurança
LID_sell=Vender
LID_send=Enviar
LID_sendclientinfo=Enviar Informações do Cliente
LID_sendfeedback=Enviar Feedback
LID_sendticket=Enviar Ticket
LID_server=Servidor
LID_server_console=Console do servidor
LID_serverid=ID servidor
LID_servers=Servidores
LID_serveruptime=Tempo de Servidor
LID_service=Serviços
LID_setasserverdefault=Definir como servidor padrão
LID_settodefault=Definir como padrão
LID_shop=Loja
LID_showchanges=Mostrar mudanças
LID_showidcardid=Mostrar RGID
LID_showowner=Mostrar Proprietário
LID_sidearm=Arma Lateral
LID_sidearms=Armas Laterais
LID_sidearmslot=Slot de Arma Lateral
LID_sidearmslots=Slots de Arma Lateral
LID_simple=Simples
LID_siteisloading=Carregando o site
LID_slap=Tapa
LID_slay=Matar
LID_someonehasjoinedthefrequency=Alguém se juntou à frequência
LID_someonehasleftthefrequency=Alguém saiu da frequência
LID_south=Sul
#South
LID_south_short=S
LID_spawn=Spawn
LID_spawns=Spawns
LID_speakfaction=Voz da facção
LID_speakglobal=Voz Global
LID_speakgroup=Voz de grupo
LID_speaking=Falando
LID_speaklocal=Voz Local
LID_specializations=Especializações
LID_spectate=Espectar
LID_spectating=Espectando
LID_spirit=Espírito
LID_splint=Tala
LID_splinting=Remendo
LID_sqlmode=Modo SQL
LID_staff=Funcionário
LID_standing=Em pé
LID_startlevel=Nível inicial
LID_stats=Status
LID_status=Estado
LID_steamname=Nome Steam
LID_steamprofile=Perfil Steam
LID_stomach=Estômago
LID_storage=Armazenamento
LID_storagepoint=Ponto de armazenamento
LID_strength=Força
LID_structure=Estrutura
LID_submit=Enviar
LID_suffix=Sufixo
LID_suggestions=Sugestões
LID_suicide=Suicidio
LID_surrender=Render-se
LID_surrenderbehind=Render-se (atrás)
LID_swep=SWEP
LID_sweps=SWEPs
LID_swepsatspawn=SWEPs no Spawn
LID_switchview=Mudar visão
LID_syringe=Seringa
LID_tab=Aba
LID_tabs=Abas
LID_talent=Talento
LID_talents=Talentos
#general word: target
LID_target=Alvo
LID_teleporter=Teletransportador
LID_text=Texto
LID_thecollectionidismissing=O CollectionID está faltando
LID_thickness=Espessura
LID_thinking=Pensando
LID_thirsty=Com sede
LID_ticket=Ticket
LID_tickets=Tickets
LID_ticketsmenu=Menu de Tickets
LID_tieup=Atar
LID_time=Tempo
LID_timeinhou=Tempo em horas
LID_timeinmin=Tempo em minutos
LID_timeinsec=Tempo em segundos
LID_title=Titulo
LID_to=Para
LID_toggle=Interruptor
LID_togglemouse=Ligar mouse on/off
LID_tool=Ferramenta
LID_tools=Ferramentas
LID_totaluptime=Tempo total do Servidor
LID_tpp=Terceira pessoa
LID_tpto=Teleportar para
LID_trade=Trocar
LID_trading=Trocando
LID_translator=Tradutor
LID_turnviewingangletotheleft=Gire o ângulo de visão para a esquerda
LID_turnviewingangletotheright=Gire o ângulo de visão para a direita
LID_type=Tipo
LID_typing=Digitando
LID_unarmed=Desarmado
LID_unassigned=Não atribuído
LID_unblind=Desvendar
LID_uncloak=Descobrir
LID_unfreeze=Descongelado
LID_ungod=God off
LID_unjail=Desprender
LID_unleash=Separar
LID_unlock=Destravar
LID_unlocked=Destravado
LID_unlockeddoor=Porta Destrancada
LID_unlockedvehicle=Veículo destrancado
LID_unlocking=Destravando
LID_unragdoll=Ragdoll off
LID_updateserver=Atualizar Servidor
LID_upgrade=Atualizar
LID_use=Usar
LID_user=Usuario
LID_usergroup=Grupo de Usuário
LID_usergroups=Grupo de Usuarios
LID_username=Nome de usuário
LID_value=Valor
LID_vehicle=veículo
LID_vehicles=veículos
LID_viewingangle=Angulo de visão
LID_viewingheight=Altura da visão
LID_viewingposition=Posição da visão
LID_viewingpositiontotheleft=Visualizando posição à esquerda
LID_viewingpositiontotheright=Visualizando posição à direita
LID_violation=Violação
LID_violations=Violações
LID_visibility=Visibilidade
LID_visible=Visivel
LID_voice=Voz
LID_voicechat=Chat de voz
LID_voicechatisdisabled=Chat de voz está desativado
LID_voicechatradio=Rádio por voz
LID_voicemodule=Módulo de Voz (Inferior Direito)
LID_voicerangedn=Diminuir alcance de voz
LID_voicerangeup=Aumentar alcance de voz
LID_wantstherole=%NAME% quer o cargo %ROLE%
LID_warning=Aviso
LID_warnings=Avisos
LID_weapon=Arma
LID_weaponchest=Baú de Armas
LID_weaponlowered=Arma abaixada
LID_weaponlowering=Abaixando arma
LID_weapons=Armas
LID_weight=Peso
LID_welcome=Bem Vindo
LID_welcomeagentx=Bem-vindo Agente %NAME%
LID_west=Oeste
#West
LID_west_short=O
LID_whisper=Sussurrar
LID_whitelist=Lista branca
LID_width=Largura
LID_wip=Ainda em Desenvolvimento
LID_workshopversion=Versão Workshop
LID_xactive=X Ativos
LID_xchannelactive=X Canais Ativos
LID_xchannelpassive=X Canais Passivos
LID_xpassive=X Passivos
LID_xpforlevelup=XP para subir de nível
LID_xpoint=%VALUE% Ponto
LID_xpoints=%VALUE% Pontos
LID_xpperkill=XP por morte
LID_xpperminute=XP por minuto
LID_xpperrevive=XP por reviver
LID_year=Ano
LID_years=Anos
LID_yell=Gritar
LID_yes=Sim
LID_you=Você
LID_youarebleeding=Você está sangrando
LID_youarenotwhitelisted=Você não está na whitelist
LID_youarespeaking=Você está falando
LID_youareusing32bit=Você está usando GMod 32Bit, por favor use o GMod 64Bit
LID_youdied=Você morreu
LID_youdonthaveakey=Você não tem a chave para isso
LID_youredeadinxseconds=Você está morto em %X% segundos
LID_youreunconsious=Você está inconsciente
LID_yourleftarmisbroken=Seu braço esquerdo está quebrado
LID_yourleftlegisbroken=Sua perna esquerda está quebrada
LID_yourrightarmisbroken=Seu braço direito está quebrado
LID_yourrightlegisbroken=Sua perna direita está quebrada
LID_youwereinvited=Você foi convidado
LID_zone=Zona
