# not empty
LID_avatar=頭像
LID_backgroundcolor=背景顏色
LID_barcolor=條形顏色
LID_border=邊框
LID_bordercolor=邊框顏色
LID_box=方框
LID_button=按鈕
LID_color_ybutton_hc=按鈕懸停顏色
LID_color_ybutton_ht=按鈕懸停文字顏色
LID_color_ybutton_nc=按鈕顏色
LID_color_ybutton_nt=按鈕文字顏色
LID_color_ybutton_pc=已選按鈕顏色
LID_color_ybutton_pt=已選按鈕文字顏色
LID_color_ybutton_sc=已選按鈕顏色
LID_color_ybutton_st=已選按鈕文字顏色
LID_color_yframe_bg=視窗背景顏色
LID_color_yframe_hb=視窗標題顏色
LID_color_yframe_hi=視窗高亮顏色
LID_color_yframe_ht=視窗標題文字顏色
LID_color_yframe_nc=視窗預設顏色
LID_color_yframe_pc=面板顏色
LID_design=設計
LID_extra=額外
LID_font=字型
LID_grid=網格
LID_gridsize=網格大小
LID_groupbox=群組框
LID_headerheight=標題高度
LID_interface=介面
LID_label=標籤
LID_panel=面板
LID_preview=預覽
LID_realtime=即時
LID_rolename=角色名稱
LID_rounded=圓角
LID_style=樣式
LID_switch=開關
LID_textbordercolor=文字邊框顏色
LID_textcolor=文字顏色
LID_textposition=文字位置
LID_textsize=文字大小
LID_transparent=透明
LID_window=視窗
