# not empty
LID_avatar=头像
LID_backgroundcolor=背景颜色
LID_barcolor=条形颜色
LID_border=边框
LID_bordercolor=边框颜色
LID_box=方框
LID_button=按钮
LID_color_ybutton_hc=按钮悬停颜色
LID_color_ybutton_ht=按钮悬停文字颜色
LID_color_ybutton_nc=按钮颜色
LID_color_ybutton_nt=按钮文字颜色
LID_color_ybutton_pc=按钮选中颜色
LID_color_ybutton_pt=按钮选中文字颜色
LID_color_ybutton_sc=按钮选中颜色
LID_color_ybutton_st=按钮选中文字颜色
LID_color_yframe_bg=窗口背景颜色
LID_color_yframe_hb=窗口标题颜色
LID_color_yframe_hi=窗口高亮颜色
LID_color_yframe_ht=窗口标题文字颜色
LID_color_yframe_nc=窗口默认颜色
LID_color_yframe_pc=面板颜色
LID_design=设计
LID_extra=额外
LID_font=字体
LID_grid=网格
LID_gridsize=网格大小
LID_groupbox=分组框
LID_headerheight=标题高度
LID_interface=界面
LID_label=标签
LID_panel=面板
LID_preview=预览
LID_realtime=实时
LID_rolename=角色名称
LID_rounded=圆角
LID_style=样式
LID_switch=开关
LID_textbordercolor=文字边框颜色
LID_textcolor=文字颜色
LID_textposition=文字位置
LID_textsize=文字大小
LID_transparent=透明
LID_window=窗口
