LID_charactercreation=Criação de personagem
LID_chooseyourfaction=Selecionar sua facção
LID_chooseyourplayermodel=Selecione seu modelo
LID_chooseyourrole=Selecione seu cargo
LID_deletecharacter=Apagar Personagem
LID_enteraname=Insira o nome
LID_nameisalreadyinuse=O nome já está em uso
LID_namelength=Comprimento do nome
