# not empty
LID_deletecharacter=刪除角色
LID_enteraname=輸入名字
LID_charactercreation=創建角色
LID_chooseyourfaction=選擇你的陣營
LID_chooseyourrole=選擇你的角色定位
LID_chooseyourplayermodel=選擇你的玩家模型
LID_namelength=名字長度
LID_nameisalreadyinuse=該名字已被使用
