# not empty
LID_charactercreation=创建角色
LID_chooseyourfaction=选择你的阵营
LID_chooseyourplayermodel=选择你的玩家模型
LID_chooseyourrole=选择你的角色定位
LID_deletecharacter=删除角色
LID_enteraname=输入名字
LID_nameisalreadyinuse=该名字已被使用
LID_namelength=名字长度
