# not empty
LID_accesssettings=存取設定
LID_gameplayrestrictions=遊戲限制
LID_gp_vehicles=可以生成載具
LID_gp_weapons=可以生成武器
LID_gp_entities=可以生成實體
LID_gp_effects=可以生成特效
LID_gp_npcs=可以生成Npcs
LID_gp_props=可以生成道具
LID_gp_ragdolls=可以生成布娃娃
LID_gp_noclip=可以使用穿牆模式
LID_gp_removetool=可以使用移除工具
LID_gp_dynamitetool=可以使用炸藥工具
LID_gp_ignite=可以使用點燃
LID_gp_drive=可以使用駕駛
LID_gp_collision=可以更改碰撞
LID_gp_gravity=可以更改重力
LID_gp_keepupright=可以更改KeepUpRight
LID_gp_bodygroups=可以更改Bodygroups
LID_gp_physgunpickup=可以用重力槍拾取
LID_gp_physgunpickupplayers=可以用重力槍拾取玩家
LID_yrp_adminaccess=可以更改其他YourRP設定
LID_gp_flashlight=可以使用手電筒
LID_gp_canseeteammatesonmap=可以在地圖上看到隊友
LID_gp_canseeenemiesonmap=可以在地圖上看到敵人
LID_gp_physgunpickupworld=可以拾取地圖實體
LID_gp_creatortool=可以使用創作者工具
LID_gp_customfunctions=可以使用自訂工具
LID_gp_canuseesp=可以使用ESP
LID_gp_canusecontextmenu=可以使用內容選單
LID_gp_canusespawnmenu=可以使用生成選單
LID_gp_physgunpickupotherowner=可以拾取他人的物品
LID_canseefrequencys=可以查看頻率
LID_physgunpickupignoreblacklist=重力槍忽略黑名單
LID_gravgunpunt=重力槍左鍵
LID_canuseesp=可以使用ESP
LID_gp_postprocess=可以使用後製處理
LID_gp_dupes=可以使用複製
LID_gp_saves=可以使用存檔
LID_physgunpickup=用重力槍拾取
LID_physgunpickupplayer=拾取玩家
LID_physgunpickupworld=拾取世界
LID_physgunpickuprank=拾取玩家
physgunpickupblacklist=已列入黑名單
