LID_accesssettings=访问设置
LID_gameplayrestrictions=游戏限制
LID_gp_vehicles=可以生成车辆
LID_gp_weapons=可以生成武器
LID_gp_entities=可以生成实体
LID_gp_effects=可以生成效果
LID_gp_npcs=可以生成Npcs
LID_gp_props=可以生成道具
LID_gp_ragdolls=可以生成废人
LID_gp_noclip=可以使用穿墙
LID_gp_removetool=可以使用删除工具
LID_gp_dynamitetool=可以使用炸药工具
LID_gp_ignite=可以使用点燃
LID_gp_drive=可以驾驶车辆
LID_gp_collision=可以改变碰撞
LID_gp_gravity=可以改变重力
LID_gp_keepupright=可以改变物品不会掉落
LID_gp_bodygroups=可以改变身体组织
LID_gp_physgunpickup=可以拾起重力枪
LID_gp_physgunpickupplayers=可以让其他玩家拾起重力枪
LID_yrp_adminaccess=可以更改其他YourRP的设置
LID_gp_flashlight=可以使用手电筒
LID_canseefrequencys=可以查看频率
LID_canuseesp=可以使用ESP
LID_gp_canseeenemiesonmap=可以在地图上看到敌人
LID_gp_canseeteammatesonmap=可以在地图上看到队友
LID_gp_canusecontextmenu=可以使用上下文菜单
LID_gp_canuseesp=可以使用ESP
LID_gp_canusespawnmenu=可以使用生成菜单
LID_gp_creatortool=可以使用创造者工具
LID_gp_customfunctions=可以使用自定义工具
LID_gp_dupes=可以使用复制
LID_gp_physgunpickupotherowner=可以拾取他人的物品
LID_gp_physgunpickupworld=可以拾取地图实体
LID_gp_postprocess=可以使用后期处理
LID_gp_saves=可以使用存档
LID_gravgunpunt=重力枪左键
LID_physgunpickup=用重力枪拾取
LID_physgunpickupignoreblacklist=重力枪忽略黑名单
LID_physgunpickupplayer=拾取玩家
LID_physgunpickuprank=拾取玩家
LID_physgunpickupworld=拾取世界
physgunpickupblacklist=已列入黑名单
