LID_1day=1 Dia
LID_1hour=1 Hora
LID_changetosqlmode=Mudar para modo SQL
LID_createbackupevery=Sempre criar Backup
LID_createbackupnow=Criar backup agora
LID_droptablesandchangelevel=Largar tabelas e mudar nivel
LID_external=Externo
LID_othertables=Outras tabelas
LID_removebackupolderthen=Remover backup antigo
LID_xdays=%amount% Dias
LID_xhours=%amount% Horas
LID_yourrpdatabase=Database YourRP
LID_yourrprelatedtables=Tabelas relacionadas  YourRP
LID_yourrptables=Tabelas YourRP
