# not empty
LID_1day=1 天
LID_1hour=1 小時
LID_changetosqlmode=切換至 SQL 模式
LID_createbackupevery=每隔多久建立備份
LID_createbackupnow=立即建立備份
LID_droptablesandchangelevel=刪除資料表並變更關卡
LID_external=外部
LID_othertables=其他資料表
LID_removebackupolderthen=移除早於此時間的備份
LID_xdays=%amount% 天
LID_xhours=%amount% 小時
LID_yourrpdatabase=YourRP 資料庫
LID_yourrprelatedtables=YourRP 相關資料表
LID_yourrptables=YourRP 資料表
