# not empty
LID_amountpercentage=使用百分比
LID_canusefactionvoicechat=可以使用陣營語音聊天
LID_canusefrequencies=可以使用頻率
LID_canuseglobalvoicechat=可以使用全域語音聊天
LID_canusegroupvoicechat=可以使用群組語音聊天
LID_canuserolevoicechat=可以使用角色語音聊天
LID_customflags=自訂標記
LID_dmgtype_bullet=子彈傷害
LID_dmgtype_burn=燃燒傷害
LID_dmgtype_energybeam=能量光束傷害
LID_flags=標記
LID_groupsof=%group% 的群組
LID_idstructure=ID結構
LID_isagent=是探員
LID_isinstructor=是指導員
LID_jumppower=跳躍力
LID_maingroups=主要群組
LID_maxamount=最大數量
LID_nextrank=下一階級
LID_nextranks=下一階級群組
LID_parentgroup=父群組
LID_parentrolesof=%role% 的父角色
LID_prerank=前置階級
LID_prerole=前置角色
LID_requireslevel=需要等級
LID_roleafterdeath=死亡後的角色
LID_roleondeath=死亡時的角色
LID_rolesof=%group% 的角色
LID_runspeed=跑步速度
LID_timesalary=發薪時間
LID_undergroup=下級群組
LID_undergroups=下級群組群
LID_useswhitelist=使用白名單
LID_voteable=可投票
LID_walkspeed=行走速度
