LID_amountpercentage=使用百分比
LID_canusefactionvoicechat=可以使用阵营语音
LID_canusefrequencies=可以使用频道
LID_canuseglobalvoicechat=可以使用全局语音
LID_canusegroupvoicechat=可以使用群组语音聊天
LID_canuserolevoicechat=可以使用角色语音
LID_customflags=自定义标志
LID_dmgtype_bullet=子弹伤害
LID_dmgtype_burn=灼烧伤害
LID_dmgtype_energybeam=能量光束伤害
LID_flags=标志
LID_groupsof=%group% 的组
LID_idstructure=ID结构
LID_isagent=是特工
LID_isinstructor=是教官
LID_jumppower=跳跃力
LID_maingroups=主要组
LID_maxamount=最大数量
LID_nextrank=下一军衔
LID_nextranks=下一军衔列表
LID_parentgroup=分组
LID_parentrolesof=%role% 的父角色
LID_prerank=前置军衔
LID_prerole=前置角色
LID_requireslevel=需要等级
LID_roleafterdeath=死亡后的角色
LID_roleondeath=死亡时的角色
LID_rolesof=%group% 的角色
LID_runspeed=跑步速度
LID_timesalary=薪水时间
LID_undergroup=下级组
LID_undergroups=下级组列表
LID_useswhitelist=使用白名单
LID_voteable=可投票
LID_walkspeed=行走速度
