# not empty
LID_3dvoicechat=3D語音聊天
LID_afkkicktime=AFK踢出時間
LID_antibunnyhop=防連續跳躍
LID_appearancesystem=外觀系統
LID_automaticreloadingoftheserver=伺服器自動重新載入
LID_buildingsystem=建造系統
LID_buildingsystem_3d=建造系統(3D文字)
LID_channelname=頻道名稱
LID_character_background=角色背景
LID_characterdesign=角色設計
LID_charactersmax=角色數量上限
LID_charactersmoneystart=角色起始金錢
LID_characterssettings=角色設定
LID_charactersystem=角色系統
LID_collectionid=收藏ID
LID_combinedmenu=合併選單
LID_communityservers=社群伺服器
LID_dealerscantakedamage=經銷商可受到傷害
LID_discord=Discord
LID_dropitemsondeath=死亡時掉落物品
LID_dropmoneyondeath=死亡時掉落金錢
LID_droproleitems=掉落角色物品
LID_example=範例
LID_facebook=Facebook
LID_forum=論壇
LID_gamemodename=遊戲模式名稱
LID_gamemodesettings=遊戲模式設定
LID_gamemodesystems=遊戲模式系統
LID_gamemodevisuals=遊戲模式視覺效果
LID_graffitidisabled=停用塗鴉
LID_groupvoicechatisaudiblelocally=群組語音聊天可在附近聽見
LID_hunger=飢餓
LID_hungerhealthregeneration=飢餓生命回復
LID_hungerhealthregenerationtickrate=飢餓生命回復頻率
LID_inventorysystem=物品欄系統
LID_loadingbackground=載入背景
LID_localchatrange=本地聊天範圍
LID_localgroupvoicechatdistance=本地群組語音聊天距離
LID_localvoicechatdistance=本地語音聊天距離
LID_maxamountofdroppedmoney=掉落金錢最大數量
LID_maxvoicerange=最大語音範圍
LID_messageoftheday=每日訊息
LID_moneyprinterspawnmoney=印鈔機產生的金錢
LID_moneyreset=金錢重置
LID_moneysettings=金錢設定
LID_noclipcloak=穿牆隱形
LID_noclipeffect=穿牆效果
LID_noclipmodel=穿牆模型
LID_noclipusergroup=穿牆使用者群組
LID_onlywhencook=僅在Cook遊玩時
LID_overheadinfo=頭頂資訊
LID_playerintroduction=玩家介紹
LID_playerscandropweapons=玩家可以丟棄武器
LID_playerscanswitchfaction=玩家可以切換陣營
LID_playerscanswitchrole=玩家可以切換角色
LID_playersdieonroleswitch=玩家切換角色時死亡
LID_playerspawn=PlayerSpawn(程式碼)
LID_playersstartwithdefaultrole=玩家以預設角色開始
LID_realisticsystem=真實系統
LID_removethebuildingowneratcharswitch=切換角色時移除建築物擁有者
LID_removethebuildingowneratdisconnect=斷線時移除建築物擁有者
LID_resetroleonconnect=連線時重置角色
LID_rules=規則
LID_serverlogo=伺服器標誌
LID_serversettings=伺服器設定
LID_showarmor=顯示護甲
LID_showchaticon=顯示聊天圖示
LID_showclan=顯示戰隊
LID_showcountry=顯示國家
LID_showdeaths=顯示死亡數
LID_showfactionname=顯示陣營名稱
LID_showfrags=顯示擊殺數
LID_showfrequency=顯示頻率
LID_showgroupname=顯示群組名稱
LID_showhealth=顯示生命值
LID_showlanguage=顯示語言
LID_showlevel=顯示等級
LID_showname=顯示名稱
LID_showonlytarget=僅顯示於目標
LID_showonlytargetforced=強制僅顯示於目標
LID_showoperatingsystem=顯示作業系統
LID_showplaytime=顯示遊玩時間
LID_showrolename=顯示角色名稱
LID_showusergroup=顯示使用者群組
LID_showvoiceicon=顯示語音圖示
LID_sideinfo=側邊資訊
LID_smartphonesystem=智慧型手機系統
LID_socialsettings=社群設定
LID_spawncorpseondeath=死亡時生成屍體
LID_stamina=體力
LID_steamgroup=Steam 群組
LID_suicidedisabled=停用自殺
LID_swaying=搖擺
LID_teamspeak=Teamspeak
LID_thirdpersonmaxdistance=第三人稱最大距離
LID_thirst=口渴
LID_timeremovethebuildingowneratdisconnect=斷線時移除建築物擁有者的時間
LID_ttlsweps=武器存活時間(SWEP)
LID_twitch=Twitch
LID_twitter=Twitter
LID_visual=視覺效果
LID_voicechatchannels=語音聊天頻道
LID_wantedsystem=通緝系統
LID_weaponloweringsystem=武器放低系統
LID_website=網站
LID_welcomemessage=歡迎訊息
LID_yourrpchat=YourRP 聊天
LID_yourrpcrosshair=YourRP 準星
LID_yourrphud=YourRP 介面
LID_yourrpscoreboard=YourRP 計分板
LID_youtube=Youtube
