LID_3dvoicechat=Chat de voz 3D
LID_afkkicktime=Tempo para expulsão por AFK
LID_antibunnyhop=AntiBunnyHop
LID_appearancesystem=Sistema de aparência
LID_automaticreloadingoftheserver=Servidor reinicia automaticamente
LID_buildingsystem=Sistema de construção
LID_buildingsystem_3d=Building System (3D Text)
LID_channelname=Nome Canal
LID_character_background=Fundo do personagem
LID_characterdesign=Design do Personagem
LID_charactersmax=Quantidade máxima de Personagens
LID_charactersmoneystart=Dinheiro inicial para um personagem
LID_characterssettings=Configurações de Personagens
LID_charactersystem=Sistema de Personagem
LID_collectionid=IDcoleção
LID_combinedmenu=Menu Combinado
LID_communityservers=Servidores da Comunidade
LID_dealerscantakedamage=Negociante pode receber dano
LID_discord=Discord
LID_dropitemsondeath=Largar itens ao morrer
LID_dropmoneyondeath=Largar dinheiro ao morrer
LID_droproleitems=Largar itens de cargo
LID_example=Exemplo
LID_facebook=Facebook
LID_forum=Fórum
LID_gamemodename=Nome modo de jogo
LID_gamemodesettings=Configurações de modo de jogo
LID_gamemodesystems=Sistemas de modo de jogo
LID_gamemodevisuals=Visual modo de jogo
LID_graffitidisabled=Grafiti desabilitado
LID_groupvoicechatisaudiblelocally=O chat por voz em grupo é audível localmente
LID_hunger=Fome
LID_hungerhealthregeneration=Regeneração da Fome
LID_hungerhealthregenerationtickrate=Tolerância à regeneração da saúde da fome
LID_inventorysystem=Sistema de inventario
LID_loadingbackground=Fundo de carregamento
LID_localchatrange=Distancia chat local
LID_localgroupvoicechatdistance=Distância do chat por voz de grupo local
LID_localvoicechatdistance=Distância do chat de voz local
LID_maxamountofdroppedmoney=Quantidade máxima que pode ser largada
LID_maxvoicerange=Raio de voz máximo
LID_messageoftheday=Mensagem do dia
LID_moneyprinterspawnmoney=Impressora de dinheiro gera dinheiro
LID_moneyreset=Resetar dinheiro
LID_moneysettings=Opções de dinheiro
LID_noclipcloak=Capa NoClip
LID_noclipeffect=Efeito NoClip
LID_noclipmodel=Modelo NoClip
LID_noclipusergroup=Grupo de usuários NoClip
LID_onlywhencook=Apenas quando o Cozinheiro estiver jogando
LID_overheadinfo=Informação sobre a cabeça
LID_playerintroduction=Introdução do jogador
LID_playerscandropweapons=Jogadores podem largar armas
LID_playerscanswitchfaction=Jogadores podem trocar de facção
LID_playerscanswitchrole=Jogadores pode trocar de cargos
LID_playersdieonroleswitch=Jogadores morrem ao trocar de cargos
LID_playerspawn=PlayerSpawn (Code)
LID_playersstartwithdefaultrole=Jogadores começam com o cargo padrão
LID_realisticsystem=Sistema de realismo
LID_removethebuildingowneratcharswitch=Remover o dono da construção ao trocar de personagem
LID_removethebuildingowneratdisconnect=Remove o proprietário da construção quando desconectar
LID_resetroleonconnect=Resetar cargo ao conectar
LID_rules=Regras
LID_serverlogo=Logo Servidor
LID_serversettings=Configurações de servidor
LID_showarmor=Mostrar Armadura
LID_showchaticon=Mostrar ícone de chat
LID_showclan=Mostrar Clan
LID_showcountry=Mostrar país
LID_showdeaths=Mostrar mortes
LID_showfactionname=Mostrar nome de facção
LID_showfrags=Mostrar Frags
LID_showfrequency=Mostrar frequência
LID_showgroupname=Mostrar nome de grupo
LID_showhealth=Mostrar Vida
LID_showlanguage=Mostrar lingua
LID_showlevel=Mostrar Nível
LID_showname=Mostrar Nome
LID_showonlytarget=Mostrar apenas no alvo
LID_showonlytargetforced=Forçar mostrar apenas no alvo
LID_showoperatingsystem=Mostrar sistema operacional
LID_showplaytime=Mostrar Tempo de jogo
LID_showrolename=Mostrar nome do cargo
LID_showusergroup=Mostrar grupo de usuários
LID_showvoiceicon=Mostrar ícone de voz
LID_sideinfo=Informação ao lado
LID_smartphonesystem=Sistema de celular
LID_socialsettings=Opções sociais
LID_spawncorpseondeath=Surgir corpos ao morrer
LID_stamina=Estamina
LID_steamgroup=Grupo Steam
LID_suicidedisabled=Suicídio desabilitado
LID_swaying=Balanço
LID_teamspeak=Teamspeak
LID_thirdpersonmaxdistance=Distancia máxima terceira pessoa
LID_thirst=Sede
LID_timeremovethebuildingowneratdisconnect=Tempo para remover o dono da construção quando desconectar
LID_ttlsweps=Tempo de vida SWEPs
LID_twitch=Twitch
LID_twitter=Twitter
LID_visual=Visual
LID_voicechatchannels=Canais de chat de voz
LID_wantedsystem=Sistema de Procurado
LID_weaponloweringsystem=Sistema de redução de arma
LID_website=Website
LID_welcomemessage=Mensagem de boas vindas
LID_yourrpchat=Chat YourRP
LID_yourrpcrosshair=Mira YourRP
LID_yourrphud=Hud YourRP
LID_yourrpscoreboard=Placar YourRP
LID_youtube=Youtube
