LID_3dvoicechat=3D聊天
LID_afkkicktime=挂机踢出时间
LID_antibunnyhop=禁止兔子跳
LID_appearancesystem=外观系统
LID_automaticreloadingoftheserver=自动重新加载服务器
LID_buildingsystem=建筑系统
LID_buildingsystem_3d=Building System (3D Text)
LID_channelname=频道名
LID_character_background=角色背景
LID_characterdesign=角色设计
LID_charactersmax=最大角色数量
LID_charactersmoneystart=角色初始资金
LID_characterssettings=角色设置
LID_charactersystem=角色系统
LID_collectionid=收藏ID
LID_combinedmenu=合并菜单
LID_communityservers=社区服务器
LID_dealerscantakedamage=经销商可以承受损害
LID_discord=Discord
LID_dropitemsondeath=死亡之后丢掉物品
LID_dropmoneyondeath=死亡后掉落金钱
LID_droproleitems=掉落角色物品
LID_example=例子
LID_facebook=脸书
LID_forum=论坛
LID_gamemodename=游戏模式名字
LID_gamemodesettings=游戏模式设置
LID_gamemodesystems=游戏模式系统
LID_gamemodevisuals=游戏模式视觉
LID_graffitidisabled=禁用涂鸦
LID_groupvoicechatisaudiblelocally=组语音可在本地被听到
LID_hunger=饥饿
LID_hungerhealthregeneration=饥饿健康再生
LID_hungerhealthregenerationtickrate=饥饿健康再生值
LID_inventorysystem=库存系统
LID_loadingbackground=加载背景
LID_localchatrange=本地聊天范围
LID_localgroupvoicechatdistance=本地组语音距离
LID_localvoicechatdistance=本地语音距离
LID_maxamountofdroppedmoney=最多掉落多少金钱
LID_maxvoicerange=最大语音范围
LID_messageoftheday=今日消息
LID_moneyprinterspawnmoney=印钞机生成金额
LID_moneyreset=金钱重置
LID_moneysettings=金钱设置
LID_noclipcloak=穿墙掩盖
LID_noclipeffect=穿墙效果
LID_noclipmodel=穿墙模式
LID_noclipusergroup=穿墙用户组
LID_onlywhencook=仅在Cook游玩时
LID_overheadinfo=头部信息
LID_playerintroduction=玩家介绍
LID_playerscandropweapons=玩家可以丢掉武器
LID_playerscanswitchfaction=玩家可以切换阵营
LID_playerscanswitchrole=玩家可以切换角色
LID_playersdieonroleswitch=玩家切换角色时死亡
LID_playerspawn=玩家生成(代码)
LID_playersstartwithdefaultrole=玩家以默认角色开始
LID_realisticsystem=伤害系统
LID_removethebuildingowneratcharswitch=切换角色时移除建筑所有者
LID_removethebuildingowneratdisconnect=断开连接时移除建筑所有者
LID_resetroleonconnect=连接时重置角色
LID_rules=规则
LID_serverlogo=服务器标志
LID_serversettings=服务器设置
LID_showarmor=显示护甲值
LID_showchaticon=显示聊天图标
LID_showclan=显示家族
LID_showcountry=显示国家
LID_showdeaths=显示死亡数
LID_showfactionname=显示阵营名称
LID_showfrags=显示杀敌数
LID_showfrequency=显示频道
LID_showgroupname=显示用户组名
LID_showhealth=显示生命值
LID_showlanguage=显示语言
LID_showlevel=显示等级
LID_showname=显示名字
LID_showonlytarget=仅对目标显示
LID_showonlytargetforced=强制仅对目标显示
LID_showoperatingsystem=显示操作系统
LID_showplaytime=显示玩游戏的时间
LID_showrolename=显示角色名
LID_showusergroup=显示玩家组
LID_showvoiceicon=显示语音图标
LID_sideinfo=侧面信息
LID_smartphonesystem=智能手机系统
LID_socialsettings=社区设置
LID_spawncorpseondeath=死亡时生成尸体
LID_stamina=耐力
LID_steamgroup=steam组
LID_suicidedisabled=禁止自杀
LID_swaying=摇摆
LID_teamspeak=Teamspeak
LID_thirdpersonmaxdistance=第三人称最大距离
LID_thirst=口渴
LID_timeremovethebuildingowneratdisconnect=断开连接后移除建筑所有者的时间
LID_ttlsweps=武器存活时间
LID_twitch=twitch
LID_twitter=推特
LID_visual=金额
LID_voicechatchannels=聊天频道
LID_wantedsystem=通缉系统
LID_weaponloweringsystem=放下武器系统
LID_website=网站
LID_welcomemessage=欢迎消息
LID_yourrpchat=YourRP聊天
LID_yourrpcrosshair=YourRP十字准星
LID_yourrphud=YourRP Hud
LID_yourrpscoreboard=YourRP记分牌
LID_youtube=Youtube
