# not empty
LID_generalsettings=一般設定
LID_damagesettings=傷害設定
LID_bonefracturing=骨折
LID_breakchancelegs=腿部骨折機率
LID_breakchancearms=手臂骨折機率
LID_bleeding=流血
LID_bleedingchance=流血機率
LID_customfalldamage=自訂墜落傷害
LID_headshotisdeadly=爆頭是致命的
LID_hitfactor=命中係數
LID_slowing=減速
LID_slowingtime=減速時間
LID_slowingfactor=減速係數
