LID_bleeding=Sangramento
LID_bleedingchance=Chance de sangramento
LID_bonefracturing=Quebra de ossos
LID_breakchancearms=Chance de quebra dos braços
LID_breakchancelegs=Chance de quebra das pernas
LID_customfalldamage=Dano de queda personalizado
LID_damagesettings=Configurações de dano
LID_generalsettings=Configurações Gerais
LID_headshotisdeadly=Headshot é mortal
LID_hitfactor=Fator de acerto
LID_slowing=Lentidão
LID_slowingfactor=Fator lentidão
LID_slowingtime=Tempo de Lentidão
