# not empty
LID_ab=AB
LID_abilitybar=能力条
LID_ar=AR
LID_armorbar=护甲条
LID_ba=BA
LID_batterybar=电池条
LID_castbar=施法进度条
LID_chatbox=聊天框
LID_conditionbar=状态条
LID_experiencebar=经验条
LID_frequency=频率
LID_healthbar=生命值条
LID_hp=HP
LID_hu=HU
LID_hungerbar=饥饿条
LID_hy=HY
LID_makesanannoucment=%NAME% 发布了一条公告
LID_moneybar=金钱条
LID_presstoopenname=按 %KEY% 打开: %NAME%
LID_ra=RA
LID_st=ST
LID_staminabar=耐力条
LID_th=TH
LID_thirstbar=口渴条
LID_weaponnamebar=武器名称条
LID_weaponprimarybar=主武器弹药条
LID_weaponsecondarybar=副武器弹药条
LID_xp=XP
