LID_healthbar=test
LID_armorbar=護甲條
LID_hungerbar=飢餓條
LID_thirstbar=口渴條
LID_chatbox=聊天框
LID_staminabar=耐力條
LID_moneybar=金錢條
LID_experiencebar=經驗條
LID_conditionbar=狀態條
LID_batterybar=電池條
LID_weaponnamebar=武器名稱條
LID_weaponprimarybar=主武器彈藥條
LID_weaponsecondarybar=副武器彈藥條
LID_castbar=施法進度條
LID_abilitybar=能力條
LID_hp=HP
LID_ar=AR
LID_hu=HU
LID_th=TH
LID_st=ST
LID_ab=AB
LID_xp=XP
LID_ba=BA
LID_ra=RA
LID_hy=HY
LID_presstoopenname=按 %KEY% 開啟: %NAME%
LID_makesanannoucment=%NAME% 發布了一則公告
LID_frequency=頻率
