#Ability
LID_ab=HA
#Ability can be mana, rage, energy, force, ...
LID_abilitybar=Barra de Habilidade
#Armor
LID_ar=AR
LID_armorbar=Barra de Armadura
#Batterypower
LID_ba=BA
#Battery of your laptop (90% Battery)
LID_batterybar=Barra de Energia
#Show Progress of an Activity on the hud (Example: Bandaging 0.5sec / 3.0 sec)
LID_castbar=Barra de Progresso
LID_chatbox=Caixa de texto
#Shows if you have leg broken, bleeding, ...
LID_conditionbar=Barra de Condição
#Shows how much xp needed for next level
LID_experiencebar=Barra de Experiência
LID_frequency=Frequência 
LID_healthbar=Barra de Saúde
#Health
LID_hp=HP
#Hunger
LID_hu=HU
LID_hungerbar=Barra de Fome
#Hygiene
LID_hy=HI
#%NAME% is a variable and containts the players name
LID_makesanannoucment=%NAME% fez um anúncio
#Shows money + salary
LID_moneybar=Barra de Dinheiro
#Example: Press USE to open: ChestXY | %KEY% and %NAME% are variables
LID_presstoopenname=Pressione %KEY% para abrir: %NAME%
#Radiation
LID_ra=RA
#Stamina
LID_st=ES
LID_staminabar=Barra de Estamina
#Thirst
LID_th=SE
LID_thirstbar=Barra de Sede
LID_weaponnamebar=Barra de nome de arma
#Primary Clip + Ammunation
LID_weaponprimarybar=Barra de arma principal
#Secondary Clip + Ammunation
LID_weaponsecondarybar=Barra de arma Secundaria
#ExperiencePoints
LID_xp=EXP
