# not empty
LID_settings=設定
LID_settings_client=客戶端
LID_character=角色
LID_characters=角色
LID_settings_hud=Hud
LID_keybind=按鍵綁定
LID_keybinds=按鍵綁定列表
LID_settings_serverpublic=伺服器(公開)
LID_settings_workshopcollection=創意工坊收藏
LID_settings_server=伺服器
LID_settings_general=一般
LID_settings_surface=外觀/設計
LID_settings_realistic=真實
LID_settings_money=金錢
LID_settings_licenses=證照
LID_settings_shops=商店
LID_settings_map=地圖
LID_settings_feedback=回饋
LID_settings_usergroups=使用者群組
LID_settings_groupsandroles=群組與角色
LID_settings_players=玩家
LID_settings_yourusergrouphasnopermission=您的使用者群組沒有權限
LID_settings_gotof8usergroups=前往 F8 使用者群組
LID_settings_giveyourselftheusergroup=要存取此頁面,您需要授予自己以下其中一個使用者群組: %USERGROUPS%
LID_hotkeyinuse=快捷鍵已被使用
LID_error=錯誤
LID_ok=確定
LID_settings_database=資料庫
LID_settings_status=狀態
LID_settings_yourrp_addons=YourRP 附加元件
LID_settings_server_addons=伺服器附加元件
LID_settings_server_management=伺服器管理
LID_settings_server_maintance=伺服器維護
LID_settings_server_gameplay=伺服器遊戲玩法
LID_settings_design=設計
LID_logs=日誌
LID_chooseapage=選擇一個頁面
LID_playermanagement=玩家管理
LID_management=管理
LID_administration=行政
LID_usermanagement=使用者管理
LID_moderation=管理審核
LID_weaponsystem=武器系統
