# not empty
LID_closedtickets=已關閉的工單
LID_movetoclosed=移至已關閉
LID_movetoopen=移至開啟
LID_movetowip=移至處理中
LID_opentickets=開啟中的工單
LID_settings_fb_contact=聯絡方式
LID_settings_fb_feedback=回饋
LID_settings_fb_feedbacks=回饋
LID_settings_fb_title=標題
LID_ticketsinprocess=處理中的工單
