# not empty
LID_addgroupspawnpoint=添加组出生点
LID_addjailpoint=添加监狱点
LID_addjailreleasepoint=添加释放点
LID_addrolespawnpoint=添加角色出生点
LID_groupspawnpoints=组出生点
LID_jailpoint=监狱点
LID_releasepoint=释放点
LID_rolespawnpoints=角色出生点
LID_selectgroup=选择组
LID_selectrole=选择角色
LID_storagepoints=存储点
