# not empty
LID_addrolespawnpoint=新增角色重生點
LID_addgroupspawnpoint=新增群組重生點
LID_addjailreleasepoint=新增釋放點
LID_addjailpoint=新增監獄點
LID_selectgroup=選擇群組
LID_selectrole=選擇角色
LID_jailpoint=監獄點
LID_releasepoint=釋放點
LID_rolespawnpoints=角色重生點
LID_groupspawnpoints=群組重生點
LID_storagepoints=儲存點
